mutation PhysicalHostRefreshMutation($id: String!) {
  refreshHost(input: {id: $id}) {
    output {
      hostSummary {
        status
        __typename
      }
      __typename
    }
    __typename
  }
}