<#
.SYNOPSIS
Downloads one or more VMware VMDKs from a specific recovery point.

.DESCRIPTION
Downloads one or more VMware VMDKs from a specific recovery point.
Supports two modes:
- CSV mode: reads a CSV from Get-RubrikVMDKList.ps1 and downloads VMDKs
  for rows marked with 'x' or 'y' in the Convert column.
- Manual mode: downloads a single VMDK by specifying VM ID, snapshot ID,
  and VMDK filename directly.

Uses 'aria2c' to download the files from the Rubrik cluster.
- https://aria2.github.io/
- aria2c.exe --check-certificate=false <url> -d <target directory>

.NOTES
Written by Steven Tong for community usage
GitHub: stevenctong
Date: 5/21/25
Updated: 8/3/26

Requires PowerShell 7+.

.PARAMETER RscServiceAccountJson
File path to the RSC Service Account JSON file.

.PARAMETER vmID
The VMware VM ID (FID) in RSC.

.PARAMETER snapshotID
The snapshot ID to download from.

.PARAMETER vmdkFileName
One or more VMDK filenames to download in manual mode
(e.g. '[datastore] vmname/vmname.vmdk'). Accepts an array for multi-disk VMs.
Not needed when using -vmCsvFile.

.PARAMETER vmCsvFile
Path to a CSV file generated by Get-RubrikVMDKList.ps1. Rows with 'x' or 'y'
in the Convert column will be used for the download. When provided, vmID,
snapshotID, and vmdkFileName are read from the CSV and do not need to be
specified as parameters.

.PARAMETER downloadPath
Directory to download VMDKs into.

.PARAMETER aria2cPath
Path to the aria2c.exe download utility. Default: 'C:\Rubrik\aria2c.exe'.

.PARAMETER timeoutMinutes
Maximum minutes to wait for download preparation to complete. Default: 60.

.PARAMETER vmName
Optional VM name used as a log prefix (e.g. '[rp-fileserv-01] ...'). When
called from Start-VMConversion.ps1, this is set automatically so parallel
output can be traced back to a specific VM.

.EXAMPLE
./Download-RubrikVMDK.ps1 -RscServiceAccountJson './rsc-service-account.json'
  -vmID <VMware VM ID> -snapshotID <snapshot ID>
  -vmdkFileName <vmdk files> -downloadPath <directory to download files to>
  Downloads the VMDK files for a given VMware VM and Snapshot to a target directory

.EXAMPLE
./Download-RubrikVMDK.ps1 -RscServiceAccountJson './rsc-service-account.json'
  -vmCsvFile './rubrik_vm_list-2026-07-15_1200.csv'
  -downloadPath <directory to download files to>
  Reads the CSV and downloads VMDKs for rows marked with 'x' or 'y' in the Convert column

#>

param (
  [CmdletBinding()]
  # File path to the RSC Service Account JSON
  [Parameter(Mandatory=$false)]
  [string]$RscServiceAccountJson = '',
  # VM ID
  [Parameter(Mandatory=$false)]
  [string]$vmID = '',
  # Snapshot ID
  [Parameter(Mandatory=$false)]
  [string]$snapshotID = '',
  # VMDK filename(s) to download
  [Parameter(Mandatory=$false)]
  [string[]]$vmdkFileName = @(),
  # CSV file from Get-RubrikVMDKList.ps1
  [Parameter(Mandatory=$false)]
  [string]$vmCsvFile = '',
  # Directory to download VMDKs into
  [Parameter(Mandatory=$false)]
  [string]$downloadPath = '',
  # Path to aria2c.exe download utility
  [Parameter(Mandatory=$false)]
  [string]$aria2cPath = '',
  # Max minutes to wait for download preparation
  [Parameter(Mandatory=$false)]
  [int]$timeoutMinutes = 60,
  # VM name prefix for log output (set by orchestrator)
  [Parameter(Mandatory=$false)]
  [string]$vmName = ''
)

$logPrefix = if ($vmName -ne '') { "[$vmName] " } else { '' }

if (-not (Test-Path $aria2cPath)) {
  throw "${logPrefix}aria2c not found at: $aria2cPath. Download from https://aria2.github.io/"
}

$csvMode = -not [string]::IsNullOrEmpty($vmCsvFile)

if ([string]::IsNullOrEmpty($RscServiceAccountJson) -or
    [string]::IsNullOrEmpty($downloadPath)) {
  Write-Host ""
  Write-Host "Usage (CSV mode): ./Download-RubrikVMDK.ps1" -ForegroundColor Cyan
  Write-Host "  -RscServiceAccountJson <path to RSC service account JSON>"
  Write-Host "  -vmCsvFile <path to CSV from Get-RubrikVMDKList.ps1>"
  Write-Host "  -downloadPath <directory to download to>"
  Write-Host ""
  Write-Host "Usage (manual mode): ./Download-RubrikVMDK.ps1" -ForegroundColor Cyan
  Write-Host "  -RscServiceAccountJson <path to RSC service account JSON>"
  Write-Host "  -vmID <VMware VM ID>"
  Write-Host "  -snapshotID <snapshot ID>"
  Write-Host "  -vmdkFileName <VMDK filename(s)>"
  Write-Host "  -downloadPath <directory to download to>"
  Write-Host ""
  exit
}

if (-not $csvMode -and (
    [string]::IsNullOrEmpty($vmID) -or
    [string]::IsNullOrEmpty($snapshotID) -or
    $vmdkFileName.Count -eq 0)) {
  Write-Host "Manual mode requires -vmID, -snapshotID, and -vmdkFileName." -ForegroundColor Yellow
  Write-Host "Or provide -vmCsvFile to use CSV mode instead." -ForegroundColor Yellow
  exit
}

# If CSV mode, read the CSV and extract VM info from marked rows
if ($csvMode) {
  Write-Host "${logPrefix}Reading CSV file: $vmCsvFile"
  try {
    $csvData = Import-Csv -Path $vmCsvFile -ErrorAction Stop
  } catch {
    Write-Error "${logPrefix}Failed to read CSV file: $($_.Exception.Message)"
    exit
  }
  $convertRows = @($csvData | Where-Object {
    $_.Convert -match '^[xyXY]$'
  })
  if ($convertRows.Count -eq 0) {
    throw "${logPrefix}No rows found with Convert set to 'x' or 'y' in: $vmCsvFile"
  }
  $vmID = $convertRows[0].ID
  $snapshotID = $convertRows[0].LatestBackupID
  $vmdkFileNames = @($convertRows | ForEach-Object { $_.vmdkFile })
  Write-Host "${logPrefix}CSV rows selected ($($convertRows.Count) VMDKs):" -ForegroundColor Cyan
  Write-Host "${logPrefix}  VM Name:       $($convertRows[0].Name)"
  Write-Host "${logPrefix}  VM ID:         $vmID"
  Write-Host "${logPrefix}  Snapshot ID:   $snapshotID"
  foreach ($vf in $vmdkFileNames) {
    Write-Host "${logPrefix}  VMDK File:     $vf"
  }
} else {
  $vmdkFileNames = @($vmdkFileName)
}

### RSC GQL Queries - BEGIN ###

$mutationDownloadVMDK = 'mutation VsphereDownloadVirtualMachineFilesMutation($input: DownloadVsphereVirtualMachineFilesInput!) {
  downloadVsphereVirtualMachineFiles(input: $input) {
    id
    error {
      message
      __typename
    }
    status
    __typename
  }
}'

$queryGetEvent = 'query EventSeriesListQuery($after: String, $filters: ActivitySeriesFilter, $first: Int, $sortBy: ActivitySeriesSortField, $sortOrder: SortOrder) {
  activitySeriesConnection(after: $after, first: $first, filters: $filters, sortBy: $sortBy, sortOrder: $sortOrder) {
    edges {
      cursor
      node {
        ...EventSeriesFragment
        cluster {
          id
          name
          timezone
          __typename
        }
        activityConnection(first: 50) {
          nodes {
            id
            message
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      __typename
    }
    __typename
  }
}
fragment EventSeriesFragment on ActivitySeries {
  id
  fid
  activitySeriesId
  lastUpdated
  lastActivityType
  lastActivityStatus
  objectId
  objectName
  objectType
  severity
  progress
  isCancelable
  isPolarisEventSeries
  location
  effectiveThroughput
  dataTransferred
  logicalSize
  organizations {
    id
    name
    __typename
  }
  clusterUuid
  clusterName
  __typename
}'

$varGetEvent = @{
  "filters" = @{
    "objectType" = $null
    "lastActivityStatus" = $null
    "lastActivityType" = $null
    "severity" = $null
    "clusterId" = $null
    "lastUpdatedTimeGt" = $null
    "orgIds" = $null
    "userIds" = $null
    "objectName" = $null
    "objectFid" = $null
  }
  "first" = 25
}

### RSC GQL Queries - END ###

###### RUBRIK AUTHENTICATION - BEGIN ######

if ($PSVersionTable.PSVersion.Major -lt 7) {
  throw "PowerShell 7+ is required. Current version: $($PSVersionTable.PSVersion)"
}

Write-Host "${logPrefix}Reading Service Account file: $RscServiceAccountJson"
try {
  $serviceAccountFile = Get-Content -Path "$RscServiceAccountJson" -ErrorAction Stop | ConvertFrom-Json
} catch {
  throw "Failed to read Service Account JSON at '$RscServiceAccountJson': $($_.Exception.Message)"
}

$missingFields = @()
if ($null -eq $serviceAccountFile.client_id) { $missingFields += 'client_id' }
if ($null -eq $serviceAccountFile.client_secret) { $missingFields += 'client_secret' }
if ($null -eq $serviceAccountFile.access_token_uri) { $missingFields += 'access_token_uri' }

if ($missingFields.Count -gt 0) {
  throw "Service Account JSON is missing required fields: $($missingFields -join ', ')"
}

$payload = @{
  grant_type    = "client_credentials"
  client_id     = $serviceAccountFile.client_id
  client_secret = $serviceAccountFile.client_secret
}

try {
  $response = Invoke-RestMethod -Method POST -Uri $serviceAccountFile.access_token_uri `
    -Body ($payload | ConvertTo-Json) -ContentType 'application/json' -ErrorAction Stop
} catch {
  throw "RSC authentication failed: $($_.Exception.Message)"
}

if ($null -eq $response.access_token) {
  throw "RSC returned a response but no access token was included."
}

$rubrikURL = $serviceAccountFile.access_token_uri.Replace("/api/client_token", "")

$global:rubrikConnection = @{
  accessToken = $response.access_token
  bearer = "Bearer $($response.access_token)"
  rubrikURL   = $rubrikURL
}

$endpoint = $rubrikURL + "/api/graphql"

$headers = @{
  'Content-Type'  = 'application/json'
  'Accept'        = 'application/json'
  'Authorization' = "Bearer $($response.access_token)"
}

Write-Host "${logPrefix}Connected to RSC: $rubrikURL" -ForegroundColor Green

###### RUBRIK AUTHENTICATION - END ######

$varDownloadVMDK = @{
  "input" = @{
    "config" = @{
      "fileNamesToDownload" = $vmdkFileNames
      "vmId" = $vmID
    }
    "id" = $snapshotID
  }
}

Write-Verbose "Download Mutation JSON:"
Write-Verbose ($varDownloadVMDK | ConvertTo-Json -depth 100)

$downloadStartTime = Get-Date
Write-Host ""
Write-Host "${logPrefix}Download started: $($downloadStartTime.ToString('M/d/yy h:mm:ss tt'))" -ForegroundColor Cyan
Write-Host "${logPrefix}Triggering preparation of $($vmdkFileNames.Count) VMDK file(s) on Rubrik..."
$body = @{
  query = $mutationDownloadVMDK
  variables = $varDownloadVMDK
} | ConvertTo-Json -Depth 100
$mutationResult = Invoke-RestMethod -Method POST -Uri $endpoint -Body $body -Headers $headers

if ($mutationResult.errors) {
  throw "${logPrefix}Download mutation failed: $($mutationResult.errors[0].message)"
}

$mutationData = $mutationResult.data.downloadVsphereVirtualMachineFiles
if ($mutationData.error) {
  throw "${logPrefix}Download request failed: $($mutationData.error.message)"
}
Write-Host "${logPrefix}Download request queued (status: $($mutationData.status))" -ForegroundColor Green

$varGetEvent.filters.lastActivityType = @('RECOVERY')
$varGetEvent.filters.objectFid = @("$vmID")

Write-Host "${logPrefix}Waiting for 15 seconds then checking events..."
Start-Sleep -Seconds 15
Write-Host "${logPrefix}Getting the most recent recovery events for the VM..."
$body = @{
  query = $queryGetEvent
  variables = $varGetEvent
} | ConvertTo-Json -Depth 100
$events = (Invoke-RestMethod -Method POST -Uri $endpoint -Body $body -Headers $headers).data.activitySeriesConnection.edges.node

Write-Host "${logPrefix}Checking events for the file download..."
$recoveryEvent = $null
foreach ($e in $events) {
  $mes = $e.activityConnection.nodes[-1].message
  if ([string]::IsNullOrEmpty($mes)) { continue }
  foreach ($vf in $vmdkFileNames) {
    if ($mes.contains($vf)) {
      $recoveryEvent = $e
      break
    }
  }
  if ($null -ne $recoveryEvent) { break }
}

if ($null -eq $recoveryEvent) {
  throw "${logPrefix}No recovery event found for: $($vmdkFileNames -join ', ')"
}
$eventID = $recoveryEvent.id
$timeZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("Eastern Standard Time")
$lastUpdatedEST = [System.TimeZoneInfo]::ConvertTimeFromUtc($recoveryEvent.LastUpdated, $timeZone)
Write-Host "${logPrefix}Recovery event found for: $($recoveryEvent.objectName)"
Write-Host "${logPrefix}Last updated (EST): $lastUpdatedEST"
$progressStr = if ($recoveryEvent.progress) { " ($($recoveryEvent.progress))" } else { '' }
$prepElapsed = [System.Diagnostics.Stopwatch]::StartNew()
Write-Host "${logPrefix}$($recoveryEvent.LastActivityStatus)$progressStr"
$waitedSeconds = 0
while ($recoveryEvent.LastActivityStatus -ne 'SUCCESS') {
  if ($recoveryEvent.LastActivityStatus -in @('FAILURE', 'CANCELED')) {
    throw "${logPrefix}Recovery event status: $($recoveryEvent.LastActivityStatus)"
  }
  if ($waitedSeconds -ge ($timeoutMinutes * 60)) {
    throw "${logPrefix}Timed out after $timeoutMinutes minutes waiting for download to complete."
  }
  $elapsedMin = [math]::Round($prepElapsed.Elapsed.TotalMinutes, 1)
  Write-Host "${logPrefix}$($recoveryEvent.LastActivityStatus)$progressStr - ${elapsedMin} min elapsed, waiting 60s..." -ForegroundColor DarkGray
  Start-Sleep -Seconds 60
  $waitedSeconds += 60
  $body = @{
    query = $queryGetEvent
    variables = $varGetEvent
  } | ConvertTo-Json -Depth 100
  $events = (Invoke-RestMethod -Method POST -Uri $endpoint -Body $body -Headers $headers).data.activitySeriesConnection.edges.node
  $recoveryEvent = $events | Where-Object { $_.id -eq $eventID}
  $progressStr = if ($recoveryEvent.progress) { " ($($recoveryEvent.progress))" } else { '' }
}

Write-Host ""
Write-Host "${logPrefix}Download preparation complete. Event messages:" -ForegroundColor Green
$recoveryEvent.ActivityConnection.nodes.message | ForEach-Object {
  Write-Host "${logPrefix}  $_"
}

$downloadList = @()
foreach ($e in $recoveryEvent.ActivityConnection.nodes) {
  if ($e.message -match "The file can also be downloaded through this link:\s*(.+)") {
    $dlLink = $matches[1]
    $downloadList += $dlLink
  }
}

if ($downloadList.Count -eq 0) {
  throw "${logPrefix}No download links found in the recovery event messages."
}

Write-Host ""
Write-Host "${logPrefix}Found $($downloadList.Count) file(s) to download:" -ForegroundColor Cyan
foreach ($dl in $downloadList) {
  Write-Host "${logPrefix}  $dl"
}

[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }

$clusterIP = ([System.Uri]$downloadList[0]).Host
Write-Host ""
Write-Host "${logPrefix}Creating CDM session on cluster: $clusterIP"
try {
  $cdmSession = Invoke-RestMethod -Method POST -ContentType 'application/json' -SkipCertificateCheck `
    -Uri "https://$clusterIP/api/v1/service_account/session" `
    -Body (@{ serviceAccountId = $serviceAccountFile.client_id; secret = $serviceAccountFile.client_secret } | ConvertTo-Json) `
    -ErrorAction Stop
} catch {
  throw "${logPrefix}CDM authentication failed for cluster $clusterIP : $($_.Exception.Message)"
}
Write-Host "${logPrefix}Connected to CDM cluster: $clusterIP" -ForegroundColor Green

$downloadCount = 0
$failCount = 0
Write-Host ""
for ($i = 0; $i -lt $downloadList.Count; $i++) {
  $f = $downloadList[$i]
  Write-Host "${logPrefix}[$($i + 1)/$($downloadList.Count)] Downloading: $f"
  try {
    $aria2Output = & $aria2cPath --check-certificate=false --file-allocation=none --summary-interval=60 --header="Authorization: Bearer $($cdmSession.token)" $f -d $downloadPath 2>&1
    $aria2Output | ForEach-Object { Write-Host "${logPrefix}  $_" }
    if ($LASTEXITCODE -ne 0) {
      Write-Error "${logPrefix}aria2c exited with code $LASTEXITCODE for: $f"
      $failCount++
    } else {
      $downloadCount++
    }
  } catch {
    Write-Error "${logPrefix}aria2c failed for: $f - $($_.Exception.Message)"
    $failCount++
  }
}

Write-Host ""
$downloadEndTime = Get-Date
$downloadElapsed = $downloadEndTime - $downloadStartTime
if ($failCount -eq 0) {
  Write-Host "${logPrefix}All $downloadCount file(s) downloaded to: $downloadPath" -ForegroundColor Green
} else {
  Write-Host "${logPrefix}$downloadCount file(s) downloaded, $failCount failed. Output directory: $downloadPath" -ForegroundColor Yellow
}
Write-Host "${logPrefix}Download completed: $($downloadEndTime.ToString('M/d/yy h:mm:ss tt')) (elapsed: $([math]::Round($downloadElapsed.TotalMinutes, 1)) min)" -ForegroundColor Cyan

# Clean up CDM session
try {
  Invoke-RestMethod -Method DELETE -SkipCertificateCheck `
    -Uri "https://$clusterIP/api/v1/session/$([Uri]::EscapeDataString($cdmSession.sessionId))" `
    -Headers @{ 'Authorization' = "Bearer $($cdmSession.token)"; 'Content-Type' = 'application/json' } | Out-Null
  Write-Host "${logPrefix}CDM session deleted." -ForegroundColor DarkGray
} catch {
  Write-Warning "${logPrefix}Failed to delete CDM session: $($_.Exception.Message)"
}

if ($failCount -gt 0) {
  throw "${logPrefix}aria2c download failed for $failCount of $($downloadList.Count) file(s). Check log for aria2c output."
}
