<#
.SYNOPSIS
Orchestrates parallel VMware-to-Azure VM conversion pipelines.

.DESCRIPTION
Reads a VMDK CSV from Get-RubrikVMDKList.ps1, groups VMDKs by VM, and
processes multiple VMs in parallel through the Download -> Convert -> Upload
pipeline. Tracks per-VM state in a CSV for resume/retry on failure. Each VM
gets its own log file for full diagnostic output.

The pipeline for each VM:
1. Download: triggers VMDK download from Rubrik via RSC + CDM cluster
2. Convert: converts VMDKs from VMFS format to fixed VHD using qemu-img
3. Upload: uploads all VHDs as managed disks via AzCopy direct upload, then
   creates the Azure VM with all disks attached in a single call

.NOTES
Written by Steven Tong for community usage
GitHub: stevenctong
Date: 8/2/26
Updated: 8/3/26

Requires PowerShell 7+.

Per-VM Azure settings (ResourceGroup, VNetRG, VNetName, SubnetName, NsgRG,
NsgName, VMSize, ManagedDiskSku) are specified in the CSV columns.
Shared Azure settings (subscription, location, azcopy path) are in
conversion_config.psd1.

.PARAMETER pipelineConfig
Path to a PSD1 config file (conversion_config.psd1) containing pipeline
settings. Any setting in the PSD1 is used unless explicitly overridden by
a command-line parameter. See conversion_config.psd1 for available keys.

.PARAMETER RscServiceAccountJson
File path to the RSC Service Account JSON file for VMDK downloads.

.PARAMETER vmCsvFile
Path to the VMDK CSV file generated by Get-RubrikVMDKList.ps1. Rows with
'x' or 'y' in the Convert column will be processed.

.PARAMETER workingDir
Base directory for downloads, conversions, and logs. Each VM gets a
subdirectory with download/, converted/, and a conversion.log file.

.PARAMETER throttleLimit
Maximum number of VMs to process in parallel. Default: 5.

.PARAMETER aria2cPath
Path to the aria2c download utility. Default: 'C:\Rubrik\aria2c.exe'.

.PARAMETER qemuPath
Path to the qemu-img.exe conversion tool. Default: 'C:\Program Files\qemu\qemu-img.exe'.

.PARAMETER timeoutMinutes
Maximum minutes to wait for each VM's download preparation. Default: 60.

.PARAMETER subscription
Azure subscription name or ID for the upload stage.

.PARAMETER location
Azure region (e.g., 'eastus2') for uploaded resources.

.PARAMETER azcopyPath
Path to azcopy.exe for direct-to-managed-disk upload.

.PARAMETER osType
Default OS type for uploaded VMs. Valid values: 'Windows', 'Linux'. Default: 'Windows'.

.PARAMETER skuName
Default managed disk SKU. Per-VM CSV column 'ManagedDiskSku' overrides this.

.PARAMETER RetryFailed
Re-process VMs that previously failed. Without this switch, failed VMs
are skipped on re-run.

.PARAMETER RunDownload
Run the download stage. Default: $true. Set to $false to skip downloading
when VMDKs are already present.

.PARAMETER RunConvert
Run the convert stage. Default: $true. Set to $false to skip conversion
when VHDs are already converted.

.PARAMETER RunUpload
Run the upload/VM creation stage. Default: $true. Set to $false to skip
uploading to Azure (useful for testing download and convert only).

.EXAMPLE
./Start-VMConversion.ps1 -pipelineConfig './conversion_config.psd1'
Runs using all settings from the PSD1 config file.

.EXAMPLE
./Start-VMConversion.ps1 -pipelineConfig './conversion_config.psd1' -throttleLimit 3 -RetryFailed
Runs from config file but overrides throttle limit and retries failed VMs.

.EXAMPLE
./Start-VMConversion.ps1 -pipelineConfig './conversion_config.psd1' -RunUpload $false
Runs download and convert stages only, skipping Azure upload (for testing).

#>

[CmdletBinding()]
param (
  # Path to pipeline config PSD1 (conversion_config.psd1)
  [Parameter(Mandatory=$false)]
  [string]$pipelineConfig = '',
  # File path to the RSC Service Account JSON
  [Parameter(Mandatory=$false)]
  [string]$RscServiceAccountJson = '',
  # Path to VMDK CSV from Get-RubrikVMDKList.ps1
  [Parameter(Mandatory=$false)]
  [string]$vmCsvFile = '',
  # Base directory for downloads, conversions, and logs
  [Parameter(Mandatory=$false)]
  [string]$workingDir = '',
  # Max parallel VMs
  [Parameter(Mandatory=$false)]
  [int]$throttleLimit = 5,
  # Path to aria2c.exe
  [Parameter(Mandatory=$false)]
  [string]$aria2cPath = 'F:\aria2c\aria2c.exe',
  # Path to qemu-img.exe
  [Parameter(Mandatory=$false)]
  [string]$qemuPath = 'C:\Program Files\qemu\qemu-img.exe',
  # Max minutes to wait for download preparation per VM
  [Parameter(Mandatory=$false)]
  [int]$timeoutMinutes = 60,
  # Azure subscription name or ID
  [Parameter(Mandatory=$false)]
  [string]$subscription = '',
  # Azure region
  [Parameter(Mandatory=$false)]
  [string]$location = '',
  # Path to azcopy.exe for VHD upload
  [Parameter(Mandatory=$false)]
  [string]$azcopyPath = '',
  # Azure storage account name for VHD page blob upload
  [Parameter(Mandatory=$false)]
  [string]$storageAccountName = '',
  # Blob container name in the storage account
  [Parameter(Mandatory=$false)]
  [string]$storageContainerName = '',
  # Resource group of the storage account
  [Parameter(Mandatory=$false)]
  [string]$storageAccountRG = '',
  # Use storage account page blob upload instead of direct-to-managed-disk
  [Parameter(Mandatory=$false)]
  [switch]$UseStorageAccount = $false,
  # Default OS type (Windows or Linux)
  [Parameter(Mandatory=$false)]
  [string]$osType = 'Windows',
  # Default managed disk SKU
  [Parameter(Mandatory=$false)]
  [string]$skuName = 'StandardSSD_LRS',
  # Re-process previously failed VMs
  [switch]$RetryFailed,
  # Run the download stage
  [Parameter(Mandatory=$false)]
  [bool]$RunDownload = $true,
  # Run the convert stage
  [Parameter(Mandatory=$false)]
  [bool]$RunConvert = $true,
  # Run the upload / VM creation stage
  [Parameter(Mandatory=$false)]
  [bool]$RunUpload = $true
)

# -- Load pipeline config (PSD1 values used unless overridden by params) ------

if (-not [string]::IsNullOrEmpty($pipelineConfig)) {
  if (-not (Test-Path $pipelineConfig)) {
    Write-Error "Pipeline config file not found: $pipelineConfig"
    exit
  }
  Write-Host "Loading pipeline config: $pipelineConfig" -ForegroundColor Cyan
  $pipelineCfg = Import-PowerShellDataFile -Path $pipelineConfig

  # Apply config values for any parameter not explicitly passed on the command line
  $configMap = @{
    'RscServiceAccountJson' = 'RscServiceAccountJson'
    'vmCsvFile'             = 'vmCsvFile'
    'workingDir'            = 'workingDir'
    'throttleLimit'         = 'throttleLimit'
    'aria2cPath'            = 'aria2cPath'
    'qemuPath'              = 'qemuPath'
    'timeoutMinutes'        = 'timeoutMinutes'
    'subscription'          = 'subscription'
    'location'              = 'location'
    'azcopyPath'            = 'azcopyPath'
    'storageAccountName'    = 'storageAccountName'
    'storageContainerName'  = 'storageContainerName'
    'storageAccountRG'      = 'storageAccountRG'
    'useStorageAccount'     = 'UseStorageAccount'
    'osType'                = 'osType'
    'skuName'               = 'skuName'
    'RunDownload'           = 'RunDownload'
    'RunConvert'            = 'RunConvert'
    'RunUpload'             = 'RunUpload'
  }
  foreach ($paramName in $configMap.Keys) {
    $cfgKey = $configMap[$paramName]
    if (-not $PSBoundParameters.ContainsKey($paramName) -and $pipelineCfg.ContainsKey($cfgKey)) {
      Set-Variable -Name $paramName -Value $pipelineCfg[$cfgKey]
    }
  }
}

# -- Usage --------------------------------------------------------------------

if ([string]::IsNullOrEmpty($RscServiceAccountJson) -or
    [string]::IsNullOrEmpty($vmCsvFile) -or
    [string]::IsNullOrEmpty($workingDir)) {
  Write-Host ""
  Write-Host "Usage: ./Start-VMConversion.ps1" -ForegroundColor Cyan
  Write-Host "  -pipelineConfig <path to conversion_config.psd1>"
  Write-Host "  [-throttleLimit <max parallel VMs>] (override config)"
  Write-Host "  [-RetryFailed] (re-process failed VMs)"
  Write-Host "  [-RunDownload <bool>] (default: true)"
  Write-Host "  [-RunConvert <bool>] (default: true)"
  Write-Host "  [-RunUpload <bool>] (default: true)"
  Write-Host ""
  Write-Host "All pipeline and Azure settings are in conversion_config.psd1." -ForegroundColor Cyan
  Write-Host "Per-VM Azure settings (ResourceGroup, VNet, NSG, etc.) are in the CSV." -ForegroundColor Cyan
  Write-Host ""
  exit
}

if ($PSVersionTable.PSVersion.Major -lt 7) {
  Write-Error "PowerShell 7+ is required. Current version: $($PSVersionTable.PSVersion)"
  exit
}

# -- Validate prerequisites ---------------------------------------------------

$validationErrors = @()
if (-not (Test-Path $RscServiceAccountJson)) { $validationErrors += "RSC service account not found: $RscServiceAccountJson" }
if (-not (Test-Path $vmCsvFile)) { $validationErrors += "CSV file not found: $vmCsvFile" }
if ($RunDownload -and -not (Test-Path $aria2cPath)) { $validationErrors += "aria2c not found: $aria2cPath" }
if ($RunConvert -and -not (Test-Path $qemuPath)) { $validationErrors += "qemu-img not found: $qemuPath" }
if ($RunUpload) {
  if ([string]::IsNullOrEmpty($subscription)) { $validationErrors += "subscription is required for upload (set in conversion_config.psd1)" }
  if ([string]::IsNullOrEmpty($location)) { $validationErrors += "location is required for upload (set in conversion_config.psd1)" }
  if (-not (Test-Path $azcopyPath)) { $validationErrors += "azcopy not found: $azcopyPath" }
  if ($UseStorageAccount) {
    if ([string]::IsNullOrEmpty($storageAccountName)) { $validationErrors += "storageAccountName is required with -UseStorageAccount (set in conversion_config.psd1)" }
    if ([string]::IsNullOrEmpty($storageContainerName)) { $validationErrors += "storageContainerName is required with -UseStorageAccount (set in conversion_config.psd1)" }
    if ([string]::IsNullOrEmpty($storageAccountRG)) { $validationErrors += "storageAccountRG is required with -UseStorageAccount (set in conversion_config.psd1)" }
  }
}

if ($validationErrors.Count -gt 0) {
  Write-Host "ERROR: Pre-flight validation failed:" -ForegroundColor Red
  $validationErrors | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
  exit 1
}

# Resolve to absolute paths for use inside parallel blocks
$RscServiceAccountJson = (Resolve-Path $RscServiceAccountJson).Path
$vmCsvFile = (Resolve-Path $vmCsvFile).Path
$scriptDir = $PSScriptRoot

# Create working directory if it doesn't exist
if (-not (Test-Path $workingDir)) {
  New-Item -ItemType Directory -Path $workingDir -Force | Out-Null
}
$workingDir = (Resolve-Path $workingDir).Path

# -- Start master log ---------------------------------------------------------

$logDir = Join-Path $workingDir "logs"
if (-not (Test-Path $logDir)) {
  New-Item -ItemType Directory -Path $logDir -Force | Out-Null
}
$masterLog = Join-Path $logDir "conversion_master-$(Get-Date -Format 'yyyy-MM-dd_HHmm').log"
Start-Transcript -Path $masterLog -Append | Out-Null
Write-Host "Master log: $masterLog" -ForegroundColor Cyan

# -- Read and group input CSV -------------------------------------------------

Write-Host "Reading VMDK CSV: $vmCsvFile" -ForegroundColor Cyan
$csvData = Import-Csv -Path $vmCsvFile

$convertRows = @($csvData | Where-Object { $_.Convert -match '^[xyXY]$' })
if ($convertRows.Count -eq 0) {
  Write-Host "No rows found with Convert = 'x' or 'y' in the CSV." -ForegroundColor Yellow
  exit
}

Write-Host "Found $($convertRows.Count) VMDK(s) marked for conversion" -ForegroundColor Green

# Group VMDKs by VM (keyed on VMID since names could collide across clusters)
$vmGroupHash = [ordered]@{}
foreach ($row in $convertRows) {
  $key = $row.ID
  if (-not $vmGroupHash.Contains($key)) {
    $vmGroupHash[$key] = [PSCustomObject]@{
      VMName         = $row.Name
      VMID           = $row.ID
      Cluster        = $row.Cluster
      SnapshotID     = $row.LatestBackupID
      VmdkFiles      = @()
      VmdkSizesGiB   = @()
      BootDiskVMDK   = ''
      ResourceGroup  = $row.ResourceGroup
      VNetRG         = $row.VNetRG
      VNetName       = $row.VNetName
      SubnetName     = $row.SubnetName
      NsgRG          = $row.NsgRG
      NsgName        = $row.NsgName
      VMSize         = $row.VMSize
      ManagedDiskSku = $row.ManagedDiskSku
    }
  }
  $vmGroupHash[$key].VmdkFiles += $row.vmdkFile
  $vmGroupHash[$key].VmdkSizesGiB += [double]$row.vmdkSizeGiB
  if ($row.BootDisk -match '^[xyXY]$') {
    $vmGroupHash[$key].BootDiskVMDK = $row.vmdkFile
  }
}
$vmGroups = @($vmGroupHash.Values)

Write-Host "Grouped into $($vmGroups.Count) VM(s):" -ForegroundColor Cyan
foreach ($vm in $vmGroups) {
  $totalGiB = ($vm.VmdkSizesGiB | Measure-Object -Sum).Sum
  $bootLabel = if ($vm.BootDiskVMDK -ne '') { " [boot: $(Split-Path $vm.BootDiskVMDK -Leaf)]" } else { " [no boot disk marked]" }
  Write-Host "  $($vm.VMName) ($($vm.VmdkFiles.Count) VMDK(s), $totalGiB GiB total)$bootLabel"
  for ($i = 0; $i -lt $vm.VmdkFiles.Count; $i++) {
    $leaf = Split-Path $vm.VmdkFiles[$i] -Leaf
    $size = $vm.VmdkSizesGiB[$i]
    $bootTag = if ($vm.VmdkFiles[$i] -eq $vm.BootDiskVMDK) { "  (boot)" } else { "" }
    Write-Host "    $leaf  $size GiB$bootTag" -ForegroundColor Gray
  }
}

# -- Validate per-VM Azure columns (upload stage) ------------------------------

if ($RunUpload) {
  $uploadErrors = @()
  $requiredCols = @('ResourceGroup', 'VNetRG', 'VNetName', 'SubnetName', 'NsgRG', 'NsgName', 'VMSize')
  foreach ($vm in $vmGroups) {
    foreach ($col in $requiredCols) {
      if ([string]::IsNullOrEmpty($vm.$col)) {
        $uploadErrors += "$($vm.VMName): missing '$col' in CSV"
      }
    }
  }
  if ($uploadErrors.Count -gt 0) {
    Write-Host "ERROR: Per-VM Azure columns missing in CSV (required for upload):" -ForegroundColor Red
    $uploadErrors | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    Write-Host ""
    Write-Host "Fill in these columns in the CSV for each VM before running upload." -ForegroundColor Yellow
    exit 1
  }
}

# -- Load/create state CSV ----------------------------------------------------

$stateFile = Join-Path $workingDir "conversion_state.csv"
$stateData = @{}

if (Test-Path $stateFile) {
  Write-Host "Loading existing state from: $stateFile" -ForegroundColor Yellow
  $existingState = Import-Csv -Path $stateFile
  foreach ($row in $existingState) {
    $stateData[$row.VMID] = $row
  }
}

# Initialize or update state for each VM group
$vmsToProcess = @()
foreach ($vm in $vmGroups) {
  if ($stateData.ContainsKey($vm.VMID)) {
    $existing = $stateData[$vm.VMID]
    $dlStatus = $existing.DownloadStatus
    $cvStatus = $existing.ConvertStatus
    $ulStatus = $existing.UploadStatus

    $allDone = ($dlStatus -eq 'Complete') -and ($cvStatus -eq 'Complete') -and ($ulStatus -eq 'Complete')

    if ($allDone) {
      Write-Host "  SKIP: $($vm.VMName) - all stages complete" -ForegroundColor DarkGray
      continue
    } elseif ($existing.Stage -eq 'Failed' -and -not $RetryFailed) {
      Write-Host "  SKIP: $($vm.VMName) - failed at $($existing.ErrorStage) (use -RetryFailed)" -ForegroundColor DarkGray
      continue
    } elseif ($existing.Stage -eq 'Failed') {
      Write-Host "  RETRY: $($vm.VMName)" -ForegroundColor Yellow
      $existing.Stage = 'Pending'
      $existing.ErrorMessage = ''
      $existing.ErrorStage = ''
    } else {
      Write-Host "  RESUME: $($vm.VMName)" -ForegroundColor Yellow
      $existing.Stage = 'Pending'
    }

    $vm | Add-Member -NotePropertyName 'PriorDownloadStatus' -NotePropertyValue $dlStatus -Force
    $vm | Add-Member -NotePropertyName 'PriorConvertStatus' -NotePropertyValue $cvStatus -Force
    $vm | Add-Member -NotePropertyName 'PriorUploadStatus' -NotePropertyValue $ulStatus -Force
  } else {
    Write-Host "  NEW: $($vm.VMName)" -ForegroundColor Green
    $stateData[$vm.VMID] = [PSCustomObject]@{
      VMName         = $vm.VMName
      Cluster        = $vm.Cluster
      VMID           = $vm.VMID
      SnapshotID     = $vm.SnapshotID
      VMDKCount      = $vm.VmdkFiles.Count
      BootDiskVMDK   = $vm.BootDiskVMDK
      Stage          = 'Pending'
      DownloadStatus = 'Pending'
      ConvertStatus  = 'Pending'
      UploadStatus   = 'Pending'
      AzureVMName    = ''
      HyperVGen      = ''
      ErrorStage     = ''
      ErrorMessage   = ''
      StartTime      = ''
      EndTime        = ''
    }
    $vm | Add-Member -NotePropertyName 'PriorDownloadStatus' -NotePropertyValue 'Pending' -Force
    $vm | Add-Member -NotePropertyName 'PriorConvertStatus' -NotePropertyValue 'Pending' -Force
    $vm | Add-Member -NotePropertyName 'PriorUploadStatus' -NotePropertyValue 'Pending' -Force
  }

  # Show stage plan
  $stages = @('Download', 'Convert', 'Upload')
  $priors = @($vm.PriorDownloadStatus, $vm.PriorConvertStatus, $vm.PriorUploadStatus)
  $runFlags = @($RunDownload, $RunConvert, $RunUpload)
  $stageLabels = @()
  for ($i = 0; $i -lt 3; $i++) {
    $lbl = "$($stages[$i]): $($priors[$i])"
    if ($priors[$i] -ne 'Complete') {
      $lbl += if ($runFlags[$i]) { ' -> run' } else { ' (off)' }
    }
    $stageLabels += $lbl
  }
  Write-Host "    $($stageLabels -join ' | ')"

  $vmsToProcess += $vm
}

# Write initial state
$stateData.Values | Export-Csv -Path $stateFile -NoTypeInformation

if ($vmsToProcess.Count -eq 0) {
  Write-Host "No VMs to process." -ForegroundColor Yellow
  exit
}

Write-Host ""
Write-Host "$($vmsToProcess.Count) VM(s) to process with throttle limit $throttleLimit" -ForegroundColor Green

# -- Azure pre-flight auth ----------------------------------------------------

if ($RunUpload) {
  Write-Host "Authenticating to Azure subscription: $subscription" -ForegroundColor Cyan
  try {
    Connect-AzAccount -Subscription $subscription -ErrorAction Stop | Out-Null
  } catch {
    Write-Host "ERROR: Azure login failed: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
  }
  $azContext = Get-AzContext
  Write-Host "Azure: $($azContext.Account.Id) ($($azContext.Subscription.Name))" -ForegroundColor Green
} else {
  Write-Host "Skipping Azure login (RunUpload = false)" -ForegroundColor DarkGray
}
Write-Host ""

# -- Launch parallel VM pipelines ---------------------------------------------

Write-Host "======================================================================" -ForegroundColor Cyan
Write-Host "Starting parallel VM conversion pipelines" -ForegroundColor Cyan
Write-Host "======================================================================" -ForegroundColor Cyan
Write-Host ""

$pipelineStart = Get-Date

$job = $vmsToProcess | ForEach-Object -Parallel {
  $vm = $_
  $scriptDir = $using:scriptDir
  $workingDir = $using:workingDir
  $stateFile = $using:stateFile
  $RscServiceAccountJson = $using:RscServiceAccountJson
  $aria2cPath = $using:aria2cPath
  $qemuPath = $using:qemuPath
  $timeoutMinutes = $using:timeoutMinutes
  $subscription = $using:subscription
  $location = $using:location
  $azcopyPath = $using:azcopyPath
  $storageAccountName = $using:storageAccountName
  $storageContainerName = $using:storageContainerName
  $storageAccountRG = $using:storageAccountRG
  $UseStorageAccount = $using:UseStorageAccount
  $osType = $using:osType
  $defaultSkuName = $using:skuName
  $runDownload = $using:RunDownload
  $runConvert = $using:RunConvert
  $runUpload = $using:RunUpload

  # Helper to update state CSV with mutex
  function Update-State {
    param($updates)
    $mutex = [System.Threading.Mutex]::new($false, "VMConversionState")
    try {
      $mutex.WaitOne() | Out-Null
      $rows = Import-Csv -Path $stateFile
      foreach ($row in $rows) {
        if ($row.VMID -eq $vm.VMID) {
          foreach ($key in $updates.Keys) {
            $row.$key = $updates[$key]
          }
        }
      }
      $rows | Export-Csv -Path $stateFile -NoTypeInformation
    } finally {
      $mutex.ReleaseMutex()
    }
  }

  # Set up VM working directories
  $vmDir = Join-Path $workingDir $vm.VMName
  $downloadDir = Join-Path $vmDir "download"
  $convertedDir = Join-Path $vmDir "converted"
  $logFile = Join-Path $vmDir "conversion.log"

  New-Item -ItemType Directory -Path $downloadDir -Force | Out-Null
  New-Item -ItemType Directory -Path $convertedDir -Force | Out-Null

  # Start logging
  Start-Transcript -Path $logFile -Append | Out-Null

  $startTime = Get-Date
  Update-State @{ Stage = 'Download'; StartTime = $startTime.ToString('yyyy-MM-dd HH:mm:ss') }

  Write-Host "[$($vm.VMName)] Starting pipeline ($($vm.VmdkFiles.Count) VMDK(s))" -ForegroundColor Cyan

  $result = [PSCustomObject]@{
    VMName       = $vm.VMName
    Stage        = 'Complete'
    ErrorStage   = ''
    ErrorMessage = ''
    AzureVMName  = ''
    HyperVGen    = ''
  }

  $currentStage = 'Download'

  try {
    # -- Stage 1: Download --------------------------------------------------
    if ($runDownload -and $vm.PriorDownloadStatus -ne 'Complete') {
      Write-Host "[$($vm.VMName)] Stage 1: Downloading $($vm.VmdkFiles.Count) VMDK(s)..." -ForegroundColor Green
      Update-State @{ Stage = 'Download'; DownloadStatus = 'InProgress' }

      & "$scriptDir\Download-RubrikVMDK.ps1" `
        -RscServiceAccountJson $RscServiceAccountJson `
        -vmID $vm.VMID `
        -snapshotID $vm.SnapshotID `
        -vmdkFileName $vm.VmdkFiles `
        -downloadPath $downloadDir `
        -aria2cPath $aria2cPath `
        -timeoutMinutes $timeoutMinutes `
        -vmName $vm.VMName

      # Verify downloaded files exist (sub-scripts use exit, not exit 1)
      $downloadedFiles = @(Get-ChildItem -Path $downloadDir -Filter '*-flat.vmdk' -ErrorAction SilentlyContinue)
      if ($downloadedFiles.Count -eq 0) {
        throw "Download failed: no VMDK data files found in $downloadDir"
      }
      Write-Host "[$($vm.VMName)] Downloaded $($downloadedFiles.Count) VMDK data file(s)" -ForegroundColor Green

      Update-State @{ DownloadStatus = 'Complete' }
      Write-Host "[$($vm.VMName)] Download complete" -ForegroundColor Green
    } elseif ($vm.PriorDownloadStatus -eq 'Complete') {
      Write-Host "[$($vm.VMName)] Skipping download (already complete)" -ForegroundColor DarkGray
    } else {
      Write-Host "[$($vm.VMName)] Skipping download (RunDownload = false)" -ForegroundColor DarkGray
      Update-State @{ DownloadStatus = 'Skipped' }
    }

    # -- Stage 2: Convert ---------------------------------------------------
    $currentStage = 'Convert'
    if ($runConvert -and $vm.PriorConvertStatus -ne 'Complete') {
      Write-Host "[$($vm.VMName)] Stage 2: Converting VMDKs to VHD..." -ForegroundColor Green
      Update-State @{ Stage = 'Convert'; ConvertStatus = 'InProgress' }

      $reportFile = Join-Path $vmDir "conversion_report.json"

      & "$scriptDir\Convert-VMDK-to-VHD.ps1" `
        -sourceDir $downloadDir `
        -targetDir $convertedDir `
        -qemuPath $qemuPath `
        -reportFile $reportFile `
        -vmName $vm.VMName

      # Verify converted files exist
      $convertedFiles = @(Get-ChildItem -Path $convertedDir -Filter '*.vhd' -ErrorAction SilentlyContinue)
      if ($convertedFiles.Count -eq 0) {
        throw "Conversion failed: no VHD files found in $convertedDir"
      }
      Write-Host "[$($vm.VMName)] Converted $($convertedFiles.Count) file(s)" -ForegroundColor Green

      Update-State @{ ConvertStatus = 'Complete' }
      Write-Host "[$($vm.VMName)] Conversion complete" -ForegroundColor Green
    } elseif ($vm.PriorConvertStatus -eq 'Complete') {
      Write-Host "[$($vm.VMName)] Skipping convert (already complete)" -ForegroundColor DarkGray
    } else {
      Write-Host "[$($vm.VMName)] Skipping convert (RunConvert = false)" -ForegroundColor DarkGray
      Update-State @{ ConvertStatus = 'Skipped' }
    }

    # -- Stage 3: Upload ----------------------------------------------------
    $currentStage = 'Upload'
    if ($runUpload -and $vm.PriorUploadStatus -ne 'Complete') {
      Write-Host "[$($vm.VMName)] Stage 3: Uploading to Azure..." -ForegroundColor Green
      Update-State @{ Stage = 'Upload'; UploadStatus = 'InProgress' }

      # Read conversion report for boot disk and partition style detection
      $reportFile = Join-Path $vmDir "conversion_report.json"
      $bootVhdFile = ''
      $hyperVGen = 'V2'

      if (Test-Path $reportFile) {
        $report = Get-Content -Path $reportFile -Raw | ConvertFrom-Json
        foreach ($disk in $report) {
          if ($disk.isBootDisk) {
            $bootVhdFile = Join-Path $convertedDir $disk.targetFile
            $hyperVGen = if ($disk.partitionStyle -eq 'MBR') { 'V1' } else { 'V2' }
            break
          }
        }
      }

      # If no boot disk detected from report, check the CSV BootDisk marking
      if ([string]::IsNullOrEmpty($bootVhdFile) -and $vm.BootDiskVMDK -ne '') {
        $bootLeaf = [System.IO.Path]::GetFileNameWithoutExtension((Split-Path $vm.BootDiskVMDK -Leaf))
        $bootVhdFile = Join-Path $convertedDir "$bootLeaf.vhd"
      }

      # Collect all converted files
      $allConverted = @(Get-ChildItem -Path $convertedDir -Filter '*.vhd')
      if ($allConverted.Count -eq 0) {
        throw "No converted files found in: $convertedDir"
      }

      # If still no boot disk identified, use the first converted file
      if ([string]::IsNullOrEmpty($bootVhdFile) -or -not (Test-Path $bootVhdFile)) {
        Write-Host "[$($vm.VMName)] WARNING: No boot disk identified. Using first file: $($allConverted[0].Name)" -ForegroundColor Yellow
        $bootVhdFile = $allConverted[0].FullName
      }

      # Data disks = all converted files except the boot disk
      $bootVhdResolved = (Resolve-Path $bootVhdFile).Path
      $dataVhdFiles = @($allConverted | Where-Object { $_.FullName -ne $bootVhdResolved } | ForEach-Object { $_.FullName })

      $result.HyperVGen = $hyperVGen

      # Resolve per-VM SKU (CSV overrides default)
      $vmSkuName = if ($vm.ManagedDiskSku -ne '') { $vm.ManagedDiskSku } else { $defaultSkuName }

      # Check for Azure VM name conflict
      $azureVMName = $vm.VMName
      $existingVM = Get-AzVM -ResourceGroupName $vm.ResourceGroup -Name $azureVMName -ErrorAction SilentlyContinue
      if ($null -ne $existingVM) {
        $azureVMName = "az-$($vm.VMName)"
        Write-Host "[$($vm.VMName)] VM name conflict in resource group. Using: $azureVMName" -ForegroundColor Yellow
      }
      $result.AzureVMName = $azureVMName

      # -- Phase 1: Upload all VHDs as managed disks (no VM creation) --
      $baseUploadParams = @{
        subscription         = $subscription
        location             = $location
        resourceGroup        = $vm.ResourceGroup
        skuName              = $vmSkuName
        azcopyPath           = $azcopyPath
        SkipAzureLogin       = $true
        SkipVMCreation       = $true
      }
      if ($UseStorageAccount) {
        $baseUploadParams['storageAccountName']   = $storageAccountName
        $baseUploadParams['storageContainerName'] = $storageContainerName
        $baseUploadParams['storageAccountRG']     = $storageAccountRG
        $baseUploadParams['UseStorageAccount']    = $true
      }

      # Upload boot disk as managed disk (reuse if it already exists)
      $bootVhdBaseName = [System.IO.Path]::GetFileNameWithoutExtension($bootVhdFile)
      $bootDiskName = "$azureVMName-$bootVhdBaseName"
      $existingBootDisk = Get-AzDisk -ResourceGroupName $vm.ResourceGroup -DiskName $bootDiskName -ErrorAction SilentlyContinue
      if ($null -ne $existingBootDisk -and $existingBootDisk.ProvisioningState -eq 'Succeeded') {
        Write-Host "[$($vm.VMName)] Reusing existing boot disk: $bootDiskName" -ForegroundColor Yellow
        $bootDiskId = $existingBootDisk.Id
      } else {
        Write-Host "[$($vm.VMName)] Uploading boot disk: $(Split-Path $bootVhdFile -Leaf) (HyperVGen: $hyperVGen)" -ForegroundColor Green
        $bootParams = $baseUploadParams.Clone()
        $bootParams += @{
          vmName           = $azureVMName
          sourceVHD        = $bootVhdFile
          diskType         = 'OS'
          hyperVGeneration = $hyperVGen
          osType           = $osType
        }
        $bootDiskId = & "$scriptDir\Upload-VHD-Create-AzureVM.ps1" @bootParams
        if ([string]::IsNullOrEmpty($bootDiskId)) {
          throw "Upload failed: no managed disk ID returned for boot disk"
        }
      }
      Write-Host "[$($vm.VMName)] Boot disk: $bootDiskId" -ForegroundColor Green

      # Upload data disks as managed disks (reuse if they already exist)
      $dataDiskIds = @()
      foreach ($dataDisk in $dataVhdFiles) {
        $dataVhdBaseName = [System.IO.Path]::GetFileNameWithoutExtension($dataDisk)
        $dataDiskName = "$azureVMName-$dataVhdBaseName"
        $existingDataDisk = Get-AzDisk -ResourceGroupName $vm.ResourceGroup -DiskName $dataDiskName -ErrorAction SilentlyContinue
        if ($null -ne $existingDataDisk -and $existingDataDisk.ProvisioningState -eq 'Succeeded') {
          Write-Host "[$($vm.VMName)] Reusing existing data disk: $dataDiskName" -ForegroundColor Yellow
          $dataDiskIds += $existingDataDisk.Id
        } else {
          Write-Host "[$($vm.VMName)] Uploading data disk: $(Split-Path $dataDisk -Leaf)" -ForegroundColor Green
          $dataParams = $baseUploadParams.Clone()
          $dataParams += @{
            vmName    = $azureVMName
            sourceVHD = $dataDisk
            diskType  = 'Data'
          }
          $diskId = & "$scriptDir\Upload-VHD-Create-AzureVM.ps1" @dataParams
          if ([string]::IsNullOrEmpty($diskId)) {
            throw "Upload failed: no managed disk ID returned for data disk $(Split-Path $dataDisk -Leaf)"
          }
          $dataDiskIds += $diskId
        }
        Write-Host "[$($vm.VMName)] Data disk: $($dataDiskIds[-1])" -ForegroundColor Green
      }

      # -- Phase 2: Create VM with all disks in a single call --
      Write-Host "[$($vm.VMName)] Creating Azure VM '$azureVMName' with $($dataDiskIds.Count + 1) disk(s)..." -ForegroundColor Green

      # Get networking resources
      try {
        $vnet = Get-AzVirtualNetwork -Name $vm.VNetName -ResourceGroupName $vm.VNetRG -ErrorAction Stop
        $subnet = $vnet.Subnets | Where-Object Name -eq $vm.SubnetName
        if ($null -eq $subnet) {
          throw "Subnet '$($vm.SubnetName)' not found in VNet '$($vm.VNetName)'"
        }
        $nsgRG = if ($vm.NsgRG -ne '') { $vm.NsgRG } else { $vm.ResourceGroup }
        $nsg = Get-AzNetworkSecurityGroup -ResourceGroupName $nsgRG -Name $vm.NsgName -ErrorAction Stop
      } catch {
        throw "Failed to get networking resources: $($_.Exception.Message)"
      }

      # Create NIC (reuse if it already exists from a prior failed run)
      $nicName = "$azureVMName-nic-01"
      $nic = Get-AzNetworkInterface -Name $nicName -ResourceGroupName $vm.ResourceGroup -ErrorAction SilentlyContinue
      if ($null -eq $nic) {
        Write-Host "[$($vm.VMName)] Creating NIC: $nicName" -ForegroundColor Green
        try {
          $nic = New-AzNetworkInterface -Name $nicName -ResourceGroupName $vm.ResourceGroup `
            -Location $location -SubnetId $subnet.Id -NetworkSecurityGroupId $nsg.Id `
            -EnableAcceleratedNetworking -ErrorAction Stop
        } catch {
          throw "Failed to create NIC '$nicName': $($_.Exception.Message)"
        }
      } else {
        Write-Host "[$($vm.VMName)] Reusing existing NIC: $nicName" -ForegroundColor Yellow
      }

      # Build VM config with OS disk
      $vmConfig = New-AzVMConfig -VMName $azureVMName -VMSize $vm.VMSize
      if ($osType -eq 'Windows') {
        $vmConfig = Set-AzVMOSDisk -VM $vmConfig -ManagedDiskId $bootDiskId `
          -Name $bootDiskName -Windows -CreateOption Attach
      } else {
        $vmConfig = Set-AzVMOSDisk -VM $vmConfig -ManagedDiskId $bootDiskId `
          -Name $bootDiskName -Linux -CreateOption Attach
      }
      $vmConfig = Add-AzVMNetworkInterface -VM $vmConfig -Id $nic.Id

      # Attach all data disks
      for ($i = 0; $i -lt $dataDiskIds.Count; $i++) {
        $vmConfig = Add-AzVMDataDisk -VM $vmConfig -ManagedDiskId $dataDiskIds[$i] `
          -Lun $i -CreateOption Attach
      }

      # Create VM (single API call with all disks)
      try {
        $null = New-AzVM -ResourceGroupName $vm.ResourceGroup -Location $location -VM $vmConfig -ErrorAction Stop
      } catch {
        throw "New-AzVM failed: $($_.Exception.Message)"
      }

      # Verify the Azure VM was created
      $createdVM = Get-AzVM -ResourceGroupName $vm.ResourceGroup -Name $azureVMName -ErrorAction SilentlyContinue
      if ($null -eq $createdVM) {
        throw "VM creation failed: Azure VM '$azureVMName' not found after New-AzVM"
      }
      Write-Host "[$($vm.VMName)] Azure VM '$azureVMName' created with $($dataDiskIds.Count + 1) disk(s)" -ForegroundColor Green

      Update-State @{ UploadStatus = 'Complete' }
      Write-Host "[$($vm.VMName)] Upload complete" -ForegroundColor Green
    } elseif ($vm.PriorUploadStatus -eq 'Complete') {
      Write-Host "[$($vm.VMName)] Skipping upload (already complete)" -ForegroundColor DarkGray
    } else {
      Write-Host "[$($vm.VMName)] Skipping upload (RunUpload = false)" -ForegroundColor DarkGray
      Update-State @{ UploadStatus = 'Skipped' }
    }

    # -- Complete -----------------------------------------------------------
    $endTime = Get-Date

    # Read back sub-statuses to determine overall completion
    $mutex = [System.Threading.Mutex]::new($false, "VMConversionState")
    try {
      $mutex.WaitOne() | Out-Null
      $rows = Import-Csv -Path $stateFile
      $myRow = $rows | Where-Object { $_.VMID -eq $vm.VMID }
      $dlStatus = $myRow.DownloadStatus
      $cvStatus = $myRow.ConvertStatus
      $ulStatus = $myRow.UploadStatus
    } finally {
      $mutex.ReleaseMutex()
    }

    $allComplete = ($dlStatus -eq 'Complete') -and ($cvStatus -eq 'Complete') -and ($ulStatus -eq 'Complete')

    if ($allComplete) {
      Update-State @{
        Stage = 'Complete'
        AzureVMName = $result.AzureVMName
        HyperVGen = $result.HyperVGen
        EndTime = $endTime.ToString('yyyy-MM-dd HH:mm:ss')
      }
      Write-Host "[$($vm.VMName)] Pipeline complete! Azure VM: $($result.AzureVMName)" -ForegroundColor Green
    } else {
      $skipped = @()
      if ($dlStatus -ne 'Complete') { $skipped += 'Download' }
      if ($cvStatus -ne 'Complete') { $skipped += 'Convert' }
      if ($ulStatus -ne 'Complete') { $skipped += 'Upload' }
      Update-State @{
        Stage = 'Partial'
        EndTime = $endTime.ToString('yyyy-MM-dd HH:mm:ss')
      }
      Write-Host "[$($vm.VMName)] Pipeline partial - skipped stages: $($skipped -join ', ')" -ForegroundColor Yellow
      $result.Stage = 'Partial'
    }
  } catch {
    $errorMsg = $_.Exception.Message

    $result.Stage = 'Failed'
    $result.ErrorStage = $currentStage
    $result.ErrorMessage = $errorMsg

    Write-Host "[$($vm.VMName)] FAILED at $currentStage stage: $errorMsg" -ForegroundColor Red

    Update-State @{
      Stage = 'Failed'
      ErrorStage = $currentStage
      ErrorMessage = $errorMsg
      EndTime = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
    }
  } finally {
    Stop-Transcript | Out-Null
  }

  $result
} -ThrottleLimit $throttleLimit -AsJob

# -- Poll for results ---------------------------------------------------------

Write-Host "Pipelines running..." -ForegroundColor Cyan
Write-Host ""

$completedVMs = @()
$pollInterval = 5
while ($job.State -eq 'Running') {
  $newResults = @(Receive-Job -Job $job -ErrorAction SilentlyContinue)
  foreach ($r in $newResults) {
    if ($null -ne $r -and $null -ne $r.VMName) {
      $completedVMs += $r
      $statusColor = switch ($r.Stage) { 'Complete' { 'Green' } 'Partial' { 'Yellow' } default { 'Red' } }
      Write-Host "  $($r.VMName): $($r.Stage)" -ForegroundColor $statusColor -NoNewline
      if ($r.Stage -eq 'Complete') {
        Write-Host " -> Azure VM: $($r.AzureVMName)"
      } elseif ($r.ErrorMessage -ne '') {
        Write-Host " ($($r.ErrorStage): $($r.ErrorMessage))"
      } else {
        Write-Host ""
      }
    }
  }
  Start-Sleep -Seconds $pollInterval
  $pollInterval = 30
}

# Collect any remaining results
$finalResults = @(Receive-Job -Job $job -ErrorAction SilentlyContinue)
foreach ($r in $finalResults) {
  if ($null -ne $r -and $null -ne $r.VMName) {
    $completedVMs += $r
    $statusColor = if ($r.Stage -eq 'Complete') { 'Green' } else { 'Red' }
    Write-Host "  $($r.VMName): $($r.Stage)" -ForegroundColor $statusColor -NoNewline
    if ($r.Stage -eq 'Complete') {
      Write-Host " -> Azure VM: $($r.AzureVMName)"
    } elseif ($r.ErrorMessage -ne '') {
      Write-Host " ($($r.ErrorStage): $($r.ErrorMessage))"
    } else {
      Write-Host ""
    }
  }
}

Remove-Job -Job $job -Force

# -- Final summary ------------------------------------------------------------

$pipelineEnd = Get-Date
$elapsed = $pipelineEnd - $pipelineStart

Write-Host ""
Write-Host "======================================================================" -ForegroundColor Cyan
Write-Host "Conversion Summary" -ForegroundColor Cyan
Write-Host "======================================================================" -ForegroundColor Cyan

$successCount = ($completedVMs | Where-Object { $_.Stage -eq 'Complete' }).Count
$partialCount = ($completedVMs | Where-Object { $_.Stage -eq 'Partial' }).Count
$failCount = ($completedVMs | Where-Object { $_.Stage -eq 'Failed' }).Count

Write-Host "Total VMs processed: $($completedVMs.Count)"
Write-Host "Succeeded: $successCount" -ForegroundColor Green
if ($partialCount -gt 0) {
  Write-Host "Partial: $partialCount (has skipped stages)" -ForegroundColor Yellow
}
if ($failCount -gt 0) {
  Write-Host "Failed: $failCount" -ForegroundColor Red
}
Write-Host "Elapsed time: $([math]::Round($elapsed.TotalMinutes, 1)) minutes"
Write-Host ""

# Display table
$completedVMs | Format-Table VMName, Stage, AzureVMName, HyperVGen, ErrorStage, ErrorMessage -AutoSize

Write-Host "State file: $stateFile" -ForegroundColor Cyan
Write-Host "Working directory: $workingDir" -ForegroundColor Cyan
Write-Host ""

if ($failCount -gt 0) {
  Write-Host "To retry failed VMs, re-run with -RetryFailed" -ForegroundColor Yellow
  Write-Host "Check per-VM logs in $workingDir\<VMName>\conversion.log for details" -ForegroundColor Yellow
}

Stop-Transcript | Out-Null
