<#
.SYNOPSIS
Orchestrates file-level recovery (FLR) from Rubrik volume group backups with
state tracking for resume/retry.

.DESCRIPTION
Reads a VMDK CSV from Get-RubrikVMDKList.ps1 and processes rows where both
sourceHostname and sourceFlrDrive are filled out. Groups by unique
source/target host pairs, deduplicates drive letters, and initiates FLR via
the RSC GraphQL API.

Tracks per-job state in a CSV (flr_state.csv) so that:
- Completed and in-progress jobs are not re-initiated on re-run
- Previously initiated jobs have their status checked via the RSC event API
- Failed jobs can be retried with -RetryFailed

Fire-and-forget: the script initiates FLR and records the async request ID
but does not poll or wait for completion. Run again to check status.

Supports comma-separated drive letters in sourceFlrDrive (e.g., "G,H").
If targetFlrDrive is provided, each source drive maps to the corresponding
target drive (counts must match). If targetFlrDrive is empty, restores to
the same drive letter as the source.

.NOTES
Written by Steven Tong for community usage
GitHub: stevenctong
Date: 8/18/26
Updated: 8/18/26

Requires PowerShell 7+.

.PARAMETER RscServiceAccountJson
File path to the RSC Service Account JSON file.

.PARAMETER vmCsvFile
Path to the VMDK CSV file generated by Get-RubrikVMDKList.ps1.

.PARAMETER workingDir
Directory for state file (flr_state.csv) and logs.

.PARAMETER RetryFailed
Re-process previously failed FLR jobs.

.PARAMETER CheckOnly
Only check status of previously initiated jobs. Do not start new ones.

.EXAMPLE
./Start-FLR.ps1 -RscServiceAccountJson './rsc-service-account.json' -vmCsvFile './rubrik_vm_list-2026-08-18_1045.csv' -workingDir './flr_work'
Reads the CSV, initiates FLR for pending jobs, and tracks state in flr_work/flr_state.csv.

.EXAMPLE
./Start-FLR.ps1 -RscServiceAccountJson './rsc-service-account.json' -vmCsvFile './rubrik_vm_list-2026-08-18_1045.csv' -workingDir './flr_work' -CheckOnly
Checks the status of previously initiated FLR jobs without starting new ones.

.EXAMPLE
./Start-FLR.ps1 -RscServiceAccountJson './rsc-service-account.json' -vmCsvFile './rubrik_vm_list-2026-08-18_1045.csv' -workingDir './flr_work' -RetryFailed
Re-processes any FLR jobs that previously failed.

#>

param (
  [CmdletBinding()]
  # File path to the RSC Service Account JSON
  [Parameter(Mandatory=$false)]
  [string]$RscServiceAccountJson = '',
  # Path to VMDK CSV from Get-RubrikVMDKList.ps1
  [Parameter(Mandatory=$false)]
  [string]$vmCsvFile = '',
  # Directory for state file and logs
  [Parameter(Mandatory=$false)]
  [string]$workingDir = '',
  # Re-process previously failed jobs
  [switch]$RetryFailed,
  # Only check status, don't start new jobs
  [switch]$CheckOnly
)

$date = Get-Date

if ([string]::IsNullOrEmpty($RscServiceAccountJson) -or
    [string]::IsNullOrEmpty($vmCsvFile) -or
    [string]::IsNullOrEmpty($workingDir)) {
  Write-Host ""
  Write-Host "Usage: ./Start-FLR.ps1" -ForegroundColor Cyan
  Write-Host "  -RscServiceAccountJson <path to RSC service account JSON>"
  Write-Host "  -vmCsvFile <path to VMDK CSV from Get-RubrikVMDKList.ps1>"
  Write-Host "  -workingDir <directory for state file and logs>"
  Write-Host "  [-RetryFailed] (re-process failed jobs)"
  Write-Host "  [-CheckOnly] (only check status of initiated jobs)"
  Write-Host ""
  Write-Host "Initiates file-level recovery for CSV rows with sourceHostname and sourceFlrDrive." -ForegroundColor Gray
  Write-Host "Tracks state in workingDir/flr_state.csv for resume and status checking." -ForegroundColor Gray
  Write-Host ""
  exit
}

### RSC GQL Queries - BEGIN ###

$queryGetWinHosts = 'query PhysicalHostSelectQuery($first: Int!, $after: String, $sortBy: HierarchySortByField, $sortOrder: SortOrder, $filter: [Filter!]!) {
  physicalHosts(hostRoot: WINDOWS_HOST_ROOT, filter: $filter, first: $first, after: $after, sortBy: $sortBy, sortOrder: $sortOrder) {
    edges {
      node {
        id
        name
        connectionStatus {
          connectivity
        }
        cluster {
          id
          name
        }
        descendantConnection(typeFilter: [VolumeGroup]) {
          edges {
            node {
              id
              name
            }
          }
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}'

$queryGetSnapshots = 'query WindowsVolumeGroupSnapshotInfoQuery($snappableFid: UUID!, $snapshotGroupBy: CdmSnapshotGroupByEnum!, $timeRange: TimeRangeInput!, $timezone: Timezone, $filter: [Filter!]) {
  physicalHost(fid: $snappableFid) {
    id
    physicalChildConnection(typeFilter: [VolumeGroup], filter: $filter) {
      nodes {
        id
        ... on VolumeGroup {
          snapshotGroupBySummary(groupBy: $snapshotGroupBy, filter: {timeRange: $timeRange}, timezone: $timezone) {
            nodes {
              groupByInfo {
                ... on TimeRangeWithUnit {
                  unit
                  start
                  end
                }
              }
              cdmSnapshots {
                count
                nodes {
                  id
                  isIndexed
                  isUnindexable
                  isQuarantined
                }
              }
            }
          }
        }
      }
    }
  }
}'

$queryBrowseSnapshot = 'query BrowseSnapshotQuery($after: String, $first: Int, $path: String!, $snapshotFid: UUID!) {
  browseSnapshotFileConnection(path: $path, snapshotFid: $snapshotFid, first: $first, after: $after) {
    edges {
      cursor
      node {
        absolutePath
        displayPath
        path
        filename
        fileMode
        size
        lastModified
      }
    }
    count
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}'

$mutationFLR = 'mutation WindowsVolumeGroupRecoverFilesMutation($snapshotFid: String!, $config: VolumeGroupRestoreFilesConfigInput!) {
  restoreVolumeGroupSnapshotFiles(input: {id: $snapshotFid, config: $config}) {
    id
  }
}'

$queryGetEvents = 'query EventSeriesListQuery($filters: ActivitySeriesFilter, $first: Int) {
  activitySeriesConnection(first: $first, filters: $filters, sortBy: LAST_UPDATED, sortOrder: DESC) {
    edges {
      node {
        activitySeriesId
        lastUpdated
        lastActivityType
        lastActivityStatus
        objectName
        progress
        dataTransferred
        activityConnection(first: 1) {
          nodes {
            message
          }
        }
      }
    }
  }
}'

### RSC GQL Queries - END ###

###### RUBRIK AUTHENTICATION - BEGIN ######

if ($PSVersionTable.PSVersion.Major -lt 7) {
  throw "PowerShell 7+ is required. Current version: $($PSVersionTable.PSVersion)"
}

Write-Host "Reading Service Account file: $RscServiceAccountJson"
try {
  $serviceAccountFile = Get-Content -Path "$RscServiceAccountJson" -ErrorAction Stop | ConvertFrom-Json
} catch {
  throw "Failed to read Service Account JSON at '$RscServiceAccountJson': $($_.Exception.Message)"
}

$missingFields = @()
if ($null -eq $serviceAccountFile.client_id) { $missingFields += 'client_id' }
if ($null -eq $serviceAccountFile.client_secret) { $missingFields += 'client_secret' }
if ($null -eq $serviceAccountFile.access_token_uri) { $missingFields += 'access_token_uri' }

if ($missingFields.Count -gt 0) {
  throw "Service Account JSON is missing required fields: $($missingFields -join ', ')"
}

$payload = @{
  grant_type    = "client_credentials"
  client_id     = $serviceAccountFile.client_id
  client_secret = $serviceAccountFile.client_secret
}

try {
  $response = Invoke-RestMethod -Method POST -Uri $serviceAccountFile.access_token_uri `
    -Body ($payload | ConvertTo-Json) -ContentType 'application/json' -ErrorAction Stop
} catch {
  throw "RSC authentication failed: $($_.Exception.Message)"
}

if ($null -eq $response.access_token) {
  throw "RSC returned a response but no access token was included."
}

$rubrikURL = $serviceAccountFile.access_token_uri.Replace("/api/client_token", "")

$global:rubrikConnection = @{
  accessToken = $response.access_token
  bearer = "Bearer $($response.access_token)"
  rubrikURL   = $rubrikURL
}

$endpoint = $rubrikURL + "/api/graphql"

$headers = @{
  'Content-Type'  = 'application/json'
  'Accept'        = 'application/json'
  'Authorization' = "Bearer $($response.access_token)"
}

Write-Host "Connected to RSC: $rubrikURL" -ForegroundColor Green

###### RUBRIK AUTHENTICATION - END ######

# --- Helper function: execute GQL query ---
function Invoke-RscQuery {
  param (
    [string]$Query,
    [hashtable]$Variables
  )
  $body = @{
    query = $Query
    variables = $Variables
  } | ConvertTo-Json -Depth 100
  $result = Invoke-RestMethod -Method POST -Uri $endpoint -Body $body -Headers $headers
  if ($result.errors) {
    throw "GraphQL error: $($result.errors | ConvertTo-Json -Compress)"
  }
  return $result.data
}

# --- Read CSV and build FLR jobs ---

Write-Host "Reading CSV: $vmCsvFile"
$csvData = Import-CSV -Path $vmCsvFile

$flrRows = @($csvData | Where-Object {
  -not [string]::IsNullOrEmpty($_.sourceHostname) -and
  -not [string]::IsNullOrEmpty($_.sourceFlrDrive)
})

if ($flrRows.Count -eq 0) {
  Write-Host "No rows found with sourceHostname and sourceFlrDrive filled out. Nothing to do." -ForegroundColor Yellow
  exit
}

Write-Host "Found $($flrRows.Count) CSV row(s) with FLR configuration" -ForegroundColor Green

$flrJobs = [ordered]@{}
foreach ($row in $flrRows) {
  $targetHost = if (-not [string]::IsNullOrEmpty($row.targetRbsWinHost)) {
    $row.targetRbsWinHost
  } else {
    $row.tgtVMName
  }
  $jobKey = "$($row.sourceHostname)|$targetHost"

  $sourceDrives = @($row.sourceFlrDrive -split ',' | ForEach-Object { $_.Trim().TrimEnd(':') } | Where-Object { $_ -ne '' })
  $targetDrives = @()
  if (-not [string]::IsNullOrEmpty($row.targetFlrDrive)) {
    $targetDrives = @($row.targetFlrDrive -split ',' | ForEach-Object { $_.Trim().TrimEnd(':') } | Where-Object { $_ -ne '' })
    if ($targetDrives.Count -ne $sourceDrives.Count) {
      Write-Host "ERROR: sourceFlrDrive has $($sourceDrives.Count) drive(s) but targetFlrDrive has $($targetDrives.Count) for source '$($row.sourceHostname)'. Counts must match." -ForegroundColor Red
      continue
    }
  }

  if (-not $flrJobs.Contains($jobKey)) {
    $flrJobs[$jobKey] = @{
      sourceHostname = $row.sourceHostname
      targetHost = $targetHost
      cluster = $row.Cluster
      driveMappings = @()
    }
  }

  for ($i = 0; $i -lt $sourceDrives.Count; $i++) {
    $tgtDrive = if ($targetDrives.Count -gt 0) { $targetDrives[$i] } else { $sourceDrives[$i] }
    $mapping = @{ source = $sourceDrives[$i]; target = $tgtDrive }
    $existing = $flrJobs[$jobKey].driveMappings | Where-Object { $_.source -eq $mapping.source }
    if ($null -eq $existing) {
      $flrJobs[$jobKey].driveMappings += $mapping
    }
  }
}

Write-Host "Found $($flrJobs.Count) unique FLR job(s)" -ForegroundColor Green

# --- Load/create state CSV ---

if (-not (Test-Path $workingDir)) {
  New-Item -ItemType Directory -Path $workingDir -Force | Out-Null
}
$workingDir = (Resolve-Path $workingDir).Path

$stateFile = Join-Path $workingDir "flr_state.csv"
$stateData = [ordered]@{}

if (Test-Path $stateFile) {
  Write-Host "Loading existing state from: $stateFile" -ForegroundColor Yellow
  $existingState = Import-Csv -Path $stateFile
  foreach ($row in $existingState) {
    $stateData[$row.JobKey] = $row
  }
}

# Helper to save state
function Save-State {
  $stateData.Values | Export-Csv -Path $stateFile -NoTypeInformation
}

# Initialize state for each job from the CSV
foreach ($jobKey in $flrJobs.Keys) {
  $job = $flrJobs[$jobKey]
  $driveList = ($job.driveMappings | ForEach-Object { "$($_.source)->$($_.target)" }) -join ', '

  if (-not $stateData.Contains($jobKey)) {
    $stateData[$jobKey] = [PSCustomObject]@{
      JobKey          = $jobKey
      SourceHostname  = $job.sourceHostname
      TargetHost      = $job.targetHost
      Cluster         = $job.cluster
      Drives          = $driveList
      Status          = 'Pending'
      AsyncRequestId  = ''
      SourceHostFid   = ''
      SnapshotId      = ''
      ItemCount       = ''
      StartTime       = ''
      LastChecked     = ''
      LastMessage      = ''
      ErrorMessage    = ''
    }
  } else {
    $existing = $stateData[$jobKey]
    $existing.Drives = $driveList
    if ($existing.Status -eq 'Failed' -and $RetryFailed) {
      Write-Host "  RETRY: $($job.sourceHostname) -> $($job.targetHost)" -ForegroundColor Yellow
      $existing.Status = 'Pending'
      $existing.ErrorMessage = ''
      $existing.AsyncRequestId = ''
    }
  }
}

Save-State

# --- Status check pass: check initiated jobs ---

Write-Host ""
Write-Host "--- Status Check ---" -ForegroundColor Cyan

$initiatedJobs = @($stateData.Values | Where-Object { $_.Status -eq 'Initiated' })

if ($initiatedJobs.Count -eq 0) {
  Write-Host "No initiated jobs to check." -ForegroundColor DarkGray
} else {
  Write-Host "Checking status of $($initiatedJobs.Count) initiated job(s)..." -ForegroundColor Cyan

  foreach ($state in $initiatedJobs) {
    Write-Host "  Checking: $($state.SourceHostname) -> $($state.TargetHost)..."

    if ([string]::IsNullOrEmpty($state.SourceHostFid)) {
      Write-Host "    No SourceHostFid recorded, cannot check status." -ForegroundColor Yellow
      continue
    }

    try {
      $eventData = Invoke-RscQuery -Query $queryGetEvents -Variables @{
        filters = @{
          lastActivityType = @("Recovery")
          objectFid = @($state.SourceHostFid)
          lastUpdatedTimeGt = $state.StartTime
        }
        first = 10
      }

      $recoveryEvents = @($eventData.activitySeriesConnection.edges.node | Where-Object {
        $_.lastActivityType -eq 'Recovery'
      })

      if ($recoveryEvents.Count -eq 0) {
        Write-Host "    No recovery events found yet. Still pending." -ForegroundColor DarkGray
      } else {
        $latestEvent = $recoveryEvents[0]
        $eventStatus = $latestEvent.lastActivityStatus
        $eventMessage = ''
        if ($latestEvent.activityConnection.nodes.Count -gt 0) {
          $eventMessage = $latestEvent.activityConnection.nodes[0].message
        }
        $progress = $latestEvent.progress

        $state.LastChecked = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
        $state.LastMessage = $eventMessage

        switch ($eventStatus) {
          'Success' {
            $state.Status = 'Success'
            Write-Host "    SUCCESS: $eventMessage" -ForegroundColor Green
          }
          'PARTIAL_SUCCESS' {
            $state.Status = 'PartialSuccess'
            Write-Host "    PARTIAL SUCCESS: $eventMessage" -ForegroundColor Yellow
          }
          { $_ -in @('TaskFailed', 'Failure', 'Failed') } {
            $state.Status = 'Failed'
            $state.ErrorMessage = $eventMessage
            Write-Host "    FAILED: $eventMessage" -ForegroundColor Red
          }
          default {
            $progressLabel = if ($progress) { " ($progress)" } else { "" }
            Write-Host "    IN PROGRESS: $eventStatus$progressLabel" -ForegroundColor DarkGray
          }
        }
      }
    } catch {
      Write-Host "    ERROR checking status: $($_.Exception.Message)" -ForegroundColor Red
    }
  }

  Save-State
}

# --- Initiation pass: process pending jobs ---

if ($CheckOnly) {
  Write-Host ""
  Write-Host "CheckOnly mode - skipping initiation of new jobs." -ForegroundColor DarkGray
} else {
  Write-Host ""
  Write-Host "--- FLR Initiation ---" -ForegroundColor Cyan

  $pendingJobs = @($flrJobs.Keys | Where-Object {
    $stateData[$_].Status -eq 'Pending'
  })

  $skipCount = $flrJobs.Count - $pendingJobs.Count
  if ($skipCount -gt 0) {
    Write-Host "Skipping $skipCount job(s) (already initiated, completed, or failed)" -ForegroundColor DarkGray
  }

  if ($pendingJobs.Count -eq 0) {
    Write-Host "No pending jobs to initiate." -ForegroundColor DarkGray
  } else {
    Write-Host "Processing $($pendingJobs.Count) pending FLR job(s)..." -ForegroundColor Cyan
    Write-Host ""

    $jobIndex = 0
    foreach ($jobKey in $pendingJobs) {
      $jobIndex++
      $job = $flrJobs[$jobKey]
      $state = $stateData[$jobKey]
      $srcName = $job.sourceHostname
      $tgtName = $job.targetHost
      $driveList = ($job.driveMappings | ForEach-Object { "$($_.source)->$($_.target)" }) -join ', '

      Write-Host "=== FLR Job $jobIndex/$($pendingJobs.Count): $srcName -> $tgtName (drives: $driveList) ===" -ForegroundColor Cyan

      try {
        # Step 1: Find source host in RSC
        Write-Host "  Looking up source host '$srcName' on cluster '$($job.cluster)'..."
        $srcHostData = Invoke-RscQuery -Query $queryGetWinHosts -Variables @{
          first = 50
          filter = @(
            @{ field = "NAME"; texts = @($srcName) }
            @{ field = "IS_RELIC"; texts = @("false") }
            @{ field = "IS_REPLICATED"; texts = @("false") }
          )
          sortBy = "NAME"
          sortOrder = "ASC"
        }

        $srcHosts = @($srcHostData.physicalHosts.edges.node | Where-Object {
          $_.name -eq $srcName -and $_.cluster.name -eq $job.cluster
        })
        if ($srcHosts.Count -eq 0) {
          throw "Source host '$srcName' not found on cluster '$($job.cluster)' in RSC."
        }
        $srcHost = $srcHosts[0]
        $srcHostId = $srcHost.id
        $srcClusterId = $srcHost.cluster.id
        $srcClusterName = $srcHost.cluster.name
        $connectivity = $srcHost.connectionStatus.connectivity

        $volGroups = @($srcHost.descendantConnection.edges.node)
        if ($volGroups.Count -eq 0) {
          throw "Source host '$srcName' has no volume groups."
        }
        Write-Host "  Found source host: $srcName (cluster: $srcClusterName, status: $connectivity, VG: $($volGroups[0].name))" -ForegroundColor Green

        $state.SourceHostFid = $srcHostId

        # Step 2: Get latest volume group snapshot
        Write-Host "  Getting latest volume group snapshot..."
        $now = Get-Date
        $timeRangeStart = $now.AddDays(-90).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.fffZ")
        $timeRangeEnd = $now.AddDays(1).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.fffZ")

        $snapshotData = Invoke-RscQuery -Query $queryGetSnapshots -Variables @{
          snappableFid = $srcHostId
          snapshotGroupBy = "Day"
          timeRange = @{
            start = $timeRangeStart
            end = $timeRangeEnd
          }
          timezone = "America/Los_Angeles"
          filter = @(
            @{ field = "IS_GHOST"; texts = @("false") }
          )
        }

        $allSnapshots = @()
        foreach ($vgNode in $snapshotData.physicalHost.physicalChildConnection.nodes) {
          foreach ($group in $vgNode.snapshotGroupBySummary.nodes) {
            foreach ($snap in $group.cdmSnapshots.nodes) {
              $allSnapshots += @{
                id = $snap.id
                isIndexed = $snap.isIndexed
                groupEnd = $group.groupByInfo.end
              }
            }
          }
        }

        if ($allSnapshots.Count -eq 0) {
          throw "No volume group snapshots found in the last 90 days for '$srcName'."
        }

        $latestSnapshot = $allSnapshots | Sort-Object { $_.groupEnd } -Descending | Select-Object -First 1
        $snapshotId = $latestSnapshot.id
        Write-Host "  Latest snapshot: $snapshotId (group: $($latestSnapshot.groupEnd))" -ForegroundColor Green

        $state.SnapshotId = $snapshotId

        # Step 3: Browse snapshot root to validate drive letters
        Write-Host "  Browsing snapshot root to validate drive letters..."
        $rootBrowse = Invoke-RscQuery -Query $queryBrowseSnapshot -Variables @{
          snapshotFid = $snapshotId
          path = "/"
          first = 100
        }

        $availableDrives = @($rootBrowse.browseSnapshotFileConnection.edges.node |
          Where-Object { $_.fileMode -eq 'DIRECTORY' } |
          ForEach-Object { $_.filename.TrimEnd(':') })

        Write-Host "  Available drives in snapshot: $($availableDrives -join ', ')"

        $validMappings = @()
        foreach ($mapping in $job.driveMappings) {
          if ($mapping.source -notin $availableDrives) {
            Write-Host "  WARNING: Drive '$($mapping.source):' not found in snapshot. Skipping this drive." -ForegroundColor Yellow
          } else {
            $validMappings += $mapping
          }
        }

        if ($validMappings.Count -eq 0) {
          throw "No valid drive letters found in snapshot."
        }

        # Step 4: Browse each drive letter and collect all items (paginated)
        $restoreConfigs = @()
        foreach ($mapping in $validMappings) {
          $drivePath = "/$($mapping.source):"
          $targetDrivePath = "$($mapping.target):\"
          Write-Host "  Browsing $($mapping.source): -> restoring to $($mapping.target):\ ..."

          $allItems = @()
          $afterCursor = $null
          do {
            $browseVars = @{
              snapshotFid = $snapshotId
              path = $drivePath
              first = 1000
            }
            if ($null -ne $afterCursor) {
              $browseVars.after = $afterCursor
            }

            $browseResult = Invoke-RscQuery -Query $queryBrowseSnapshot -Variables $browseVars
            $pageItems = @($browseResult.browseSnapshotFileConnection.edges.node)
            $allItems += $pageItems
            $afterCursor = $browseResult.browseSnapshotFileConnection.pageInfo.endCursor
            $hasNext = $browseResult.browseSnapshotFileConnection.pageInfo.hasNextPage
          } while ($hasNext)

          Write-Host "    Found $($allItems.Count) item(s) on $($mapping.source):"

          foreach ($item in $allItems) {
            $restoreConfigs += @{
              path = $item.absolutePath
              restorePath = $targetDrivePath
            }
          }
        }

        if ($restoreConfigs.Count -eq 0) {
          throw "No items found to restore."
        }

        Write-Host "  Total items to restore: $($restoreConfigs.Count)"
        $state.ItemCount = $restoreConfigs.Count

        # Step 5: Find target host in RSC
        Write-Host "  Looking up target host '$tgtName' (cluster: $srcClusterName)..."
        $tgtHostData = Invoke-RscQuery -Query $queryGetWinHosts -Variables @{
          first = 50
          filter = @(
            @{ field = "NAME"; texts = @($tgtName) }
            @{ field = "IS_RELIC"; texts = @("false") }
            @{ field = "IS_REPLICATED"; texts = @("false") }
            @{ field = "CLUSTER_ID"; texts = @($srcClusterId) }
          )
          sortBy = "NAME"
          sortOrder = "ASC"
        }

        $tgtHosts = @($tgtHostData.physicalHosts.edges.node | Where-Object { $_.name -eq $tgtName })
        if ($tgtHosts.Count -eq 0) {
          throw "Target host '$tgtName' not found on cluster '$srcClusterName'."
        }
        $tgtHost = $tgtHosts[0]
        $tgtHostId = $tgtHost.id
        $tgtConnectivity = $tgtHost.connectionStatus.connectivity
        Write-Host "  Found target host: $tgtName (status: $tgtConnectivity)" -ForegroundColor Green

        if ($tgtConnectivity -ne 'CONNECTED') {
          Write-Host "  WARNING: Target host '$tgtName' is $tgtConnectivity. FLR may fail." -ForegroundColor Yellow
        }

        # Step 6: Execute FLR mutation
        Write-Host "  Initiating FLR restore ($($restoreConfigs.Count) items)..."

        $flrResult = Invoke-RscQuery -Query $mutationFLR -Variables @{
          snapshotFid = $snapshotId
          config = @{
            targetHostId = $tgtHostId
            restoreConfigs = $restoreConfigs
            shouldIgnoreError = $true
          }
        }
        $asyncId = $flrResult.restoreVolumeGroupSnapshotFiles.id
        Write-Host "  FLR initiated. Async request ID: $asyncId" -ForegroundColor Green

        $state.Status = 'Initiated'
        $state.AsyncRequestId = $asyncId
        $state.StartTime = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')

      } catch {
        Write-Host "  ERROR: $($_.Exception.Message)" -ForegroundColor Red
        $state.Status = 'Failed'
        $state.ErrorMessage = $_.Exception.Message
      }

      Save-State
      Write-Host ""
    }
  }
}

# --- Summary ---

Write-Host "======================================" -ForegroundColor Cyan
Write-Host "FLR Summary" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan

$statusGroups = $stateData.Values | Group-Object -Property Status
foreach ($group in $statusGroups | Sort-Object Name) {
  $color = switch ($group.Name) {
    'Success'        { 'Green' }
    'PartialSuccess' { 'Yellow' }
    'Initiated'      { 'Cyan' }
    'Pending'        { 'DarkGray' }
    'Failed'         { 'Red' }
    default          { 'White' }
  }
  Write-Host "  $($group.Name): $($group.Count)" -ForegroundColor $color
}
Write-Host ""

foreach ($state in $stateData.Values) {
  $statusLabel = $state.Status
  $color = switch ($statusLabel) {
    'Success'        { 'Green' }
    'PartialSuccess' { 'Yellow' }
    'Initiated'      { 'Cyan' }
    'Pending'        { 'DarkGray' }
    'Failed'         { 'Red' }
    default          { 'White' }
  }
  $detail = switch ($statusLabel) {
    'Initiated'      { "async: $($state.AsyncRequestId)" }
    'Failed'         { $state.ErrorMessage }
    'Success'        { $state.LastMessage }
    'PartialSuccess' { $state.LastMessage }
    default          { $state.Drives }
  }
  Write-Host "  [$statusLabel] $($state.SourceHostname) -> $($state.TargetHost): $detail" -ForegroundColor $color
}

Write-Host ""
Write-Host "State file: $stateFile" -ForegroundColor Cyan
Write-Host "FLR processing complete." -ForegroundColor Green
