<#
.SYNOPSIS
Orchestrates MSSQL database bulk export from Rubrik backups with state
tracking for resume/retry.

.DESCRIPTION
Reads a VMDK CSV from Get-RubrikVMDKList.ps1 and processes rows where
srcSqlInstance is filled out. Groups by unique source/target host pairs,
and initiates MSSQL bulk database export via the RSC GraphQL API.

Tracks per-job state in a CSV (sql_state.csv) so that:
- Completed and in-progress jobs are not re-initiated on re-run
- Previously initiated jobs have their status checked via the RSC event API
- Failed jobs can be retried with -RetryFailed

Fire-and-forget: the script initiates the bulk export and records the async
request ID but does not poll or wait for completion. Run again to check status.

The bulk export restores all databases from the source SQL instance to the
target SQL instance using the latest recovery point (current timestamp).

.NOTES
Written by Steven Tong for community usage
GitHub: stevenctong
Date: 8/18/26
Updated: 8/18/26

Requires PowerShell 7+.

.PARAMETER RscServiceAccountJson
File path to the RSC Service Account JSON file.

.PARAMETER vmCsvFile
Path to the VMDK CSV file generated by Get-RubrikVMDKList.ps1.

.PARAMETER workingDir
Directory for state file (sql_state.csv) and logs.

.PARAMETER RetryFailed
Re-process previously failed SQL export jobs.

.PARAMETER CheckOnly
Only check status of previously initiated jobs. Do not start new ones.

.EXAMPLE
./Start-SQLRestore.ps1 -RscServiceAccountJson './rsc-service-account.json' -vmCsvFile './rubrik_vm_list-2026-08-18_1045.csv' -workingDir './sql_work'
Reads the CSV, initiates SQL bulk export for pending jobs, and tracks state in sql_work/sql_state.csv.

.EXAMPLE
./Start-SQLRestore.ps1 -RscServiceAccountJson './rsc-service-account.json' -vmCsvFile './rubrik_vm_list-2026-08-18_1045.csv' -workingDir './sql_work' -CheckOnly
Checks the status of previously initiated SQL export jobs without starting new ones.

.EXAMPLE
./Start-SQLRestore.ps1 -RscServiceAccountJson './rsc-service-account.json' -vmCsvFile './rubrik_vm_list-2026-08-18_1045.csv' -workingDir './sql_work' -RetryFailed
Re-processes any SQL export jobs that previously failed.

#>

param (
  [CmdletBinding()]
  # File path to the RSC Service Account JSON
  [Parameter(Mandatory=$false)]
  [string]$RscServiceAccountJson = '',
  # Path to VMDK CSV from Get-RubrikVMDKList.ps1
  [Parameter(Mandatory=$false)]
  [string]$vmCsvFile = '',
  # Directory for state file and logs
  [Parameter(Mandatory=$false)]
  [string]$workingDir = '',
  # Re-process previously failed jobs
  [switch]$RetryFailed,
  # Only check status, don't start new jobs
  [switch]$CheckOnly
)

$date = Get-Date

if ([string]::IsNullOrEmpty($RscServiceAccountJson) -or
    [string]::IsNullOrEmpty($vmCsvFile) -or
    [string]::IsNullOrEmpty($workingDir)) {
  Write-Host ""
  Write-Host "Usage: ./Start-SQLRestore.ps1" -ForegroundColor Cyan
  Write-Host "  -RscServiceAccountJson <path to RSC service account JSON>"
  Write-Host "  -vmCsvFile <path to VMDK CSV from Get-RubrikVMDKList.ps1>"
  Write-Host "  -workingDir <directory for state file and logs>"
  Write-Host "  [-RetryFailed] (re-process failed jobs)"
  Write-Host "  [-CheckOnly] (only check status of initiated jobs)"
  Write-Host ""
  Write-Host "Initiates MSSQL bulk database export for CSV rows with srcSqlInstance filled out." -ForegroundColor Gray
  Write-Host "Tracks state in workingDir/sql_state.csv for resume and status checking." -ForegroundColor Gray
  Write-Host ""
  exit
}

### RSC GQL Queries - BEGIN ###

$queryGetMssqlHosts = 'query MssqlHostForClusterQuery($filter: [Filter!], $typeFilter: [HierarchyObjectTypeEnum!]) {
  mssqlTopLevelDescendants(filter: $filter, typeFilter: $typeFilter) {
    edges {
      node {
        id
        name
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}'

$queryGetMssqlHostsWithCluster = 'query MssqlHostListQuery($first: Int!, $after: String, $filter: [Filter!], $sortBy: HierarchySortByField, $sortOrder: SortOrder) {
  mssqlTopLevelDescendants(first: $first, after: $after, filter: $filter, sortBy: $sortBy, sortOrder: $sortOrder, typeFilter: [MSSQL_HOST]) {
    edges {
      node {
        id
        name
        ... on MssqlHost {
          physicalHostMetadata {
            connectionStatus {
              connectivity
            }
          }
        }
        ... on CdmHierarchyObject {
          cluster {
            id
            name
          }
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}'

$queryGetMssqlInstances = 'query MssqlInstanceForHostQuery($fid: UUID!, $filter: [Filter!], $typeFilter: [HierarchyObjectTypeEnum!]) {
  hierarchyObject(fid: $fid) {
    ... on PhysicalHost {
      childConnection: physicalChildConnection(filter: $filter, typeFilter: $typeFilter) {
        edges {
          node {
            id
            name
          }
        }
      }
    }
    ... on MssqlHost {
      childConnection: physicalChildConnection(filter: $filter, typeFilter: $typeFilter) {
        edges {
          node {
            id
            name
          }
        }
      }
    }
    ... on WindowsCluster {
      childConnection: logicalChildConnection(filter: $filter) {
        edges {
          node {
            id
            name
          }
        }
      }
    }
  }
}'

$mutationBulkExport = 'mutation MssqlDatabaseBulkExportMutation($input: BulkExportMssqlDatabasesInput!) {
  bulkExportMssqlDatabases(input: $input) {
    id
  }
}'

$queryGetEvents = 'query EventSeriesListQuery($filters: ActivitySeriesFilter, $first: Int) {
  activitySeriesConnection(first: $first, filters: $filters, sortBy: LAST_UPDATED, sortOrder: DESC) {
    edges {
      node {
        activitySeriesId
        fid
        lastUpdated
        lastActivityType
        lastActivityStatus
        objectName
        objectType
        progress
        dataTransferred
        activityConnection(first: 1) {
          nodes {
            message
          }
        }
      }
    }
  }
}'

### RSC GQL Queries - END ###

###### RUBRIK AUTHENTICATION - BEGIN ######

if ($PSVersionTable.PSVersion.Major -lt 7) {
  throw "PowerShell 7+ is required. Current version: $($PSVersionTable.PSVersion)"
}

Write-Host "Reading Service Account file: $RscServiceAccountJson"
try {
  $serviceAccountFile = Get-Content -Path "$RscServiceAccountJson" -ErrorAction Stop | ConvertFrom-Json
} catch {
  throw "Failed to read Service Account JSON at '$RscServiceAccountJson': $($_.Exception.Message)"
}

$missingFields = @()
if ($null -eq $serviceAccountFile.client_id) { $missingFields += 'client_id' }
if ($null -eq $serviceAccountFile.client_secret) { $missingFields += 'client_secret' }
if ($null -eq $serviceAccountFile.access_token_uri) { $missingFields += 'access_token_uri' }

if ($missingFields.Count -gt 0) {
  throw "Service Account JSON is missing required fields: $($missingFields -join ', ')"
}

$payload = @{
  grant_type    = "client_credentials"
  client_id     = $serviceAccountFile.client_id
  client_secret = $serviceAccountFile.client_secret
}

try {
  $response = Invoke-RestMethod -Method POST -Uri $serviceAccountFile.access_token_uri `
    -Body ($payload | ConvertTo-Json) -ContentType 'application/json' -ErrorAction Stop
} catch {
  throw "RSC authentication failed: $($_.Exception.Message)"
}

if ($null -eq $response.access_token) {
  throw "RSC returned a response but no access token was included."
}

$rubrikURL = $serviceAccountFile.access_token_uri.Replace("/api/client_token", "")

$global:rubrikConnection = @{
  accessToken = $response.access_token
  bearer = "Bearer $($response.access_token)"
  rubrikURL   = $rubrikURL
}

$endpoint = $rubrikURL + "/api/graphql"

$headers = @{
  'Content-Type'  = 'application/json'
  'Accept'        = 'application/json'
  'Authorization' = "Bearer $($response.access_token)"
}

Write-Host "Connected to RSC: $rubrikURL" -ForegroundColor Green

###### RUBRIK AUTHENTICATION - END ######

# --- Helper function: execute GQL query ---
function Invoke-RscQuery {
  param (
    [string]$Query,
    [hashtable]$Variables
  )
  $body = @{
    query = $Query
    variables = $Variables
  } | ConvertTo-Json -Depth 100
  $result = Invoke-RestMethod -Method POST -Uri $endpoint -Body $body -Headers $headers
  if ($result.errors) {
    throw "GraphQL error: $($result.errors | ConvertTo-Json -Compress)"
  }
  return $result.data
}

# --- Read CSV and build SQL export jobs ---

Write-Host "Reading CSV: $vmCsvFile"
$csvData = Import-CSV -Path $vmCsvFile

$sqlRows = @($csvData | Where-Object {
  -not [string]::IsNullOrEmpty($_.srcSqlInstance)
})

if ($sqlRows.Count -eq 0) {
  Write-Host "No rows found with srcSqlInstance filled out. Nothing to do." -ForegroundColor Yellow
  exit
}

Write-Host "Found $($sqlRows.Count) CSV row(s) with SQL configuration" -ForegroundColor Green

$sqlJobs = [ordered]@{}
foreach ($row in $sqlRows) {
  $targetHost = if (-not [string]::IsNullOrEmpty($row.targetRbsWinHost)) {
    $row.targetRbsWinHost
  } else {
    $row.tgtVMName
  }
  $jobKey = "$($row.sourceHostname)|$targetHost"

  if ($sqlJobs.Contains($jobKey)) {
    continue
  }

  $srcInstance = $row.srcSqlInstance.Trim()
  $tgtInstance = if (-not [string]::IsNullOrEmpty($row.tgtSqlInstance)) {
    $row.tgtSqlInstance.Trim()
  } else {
    $srcInstance
  }

  $dataPath = if (-not [string]::IsNullOrEmpty($row.sqlDataPath)) {
    $row.sqlDataPath.Trim()
  } else {
    ''
  }
  $logPath = if (-not [string]::IsNullOrEmpty($row.sqlLogPath)) {
    $row.sqlLogPath.Trim()
  } else {
    ''
  }

  if ([string]::IsNullOrEmpty($dataPath) -or [string]::IsNullOrEmpty($logPath)) {
    Write-Host "WARNING: Skipping $($row.sourceHostname) -> $targetHost - sqlDataPath and sqlLogPath are required." -ForegroundColor Yellow
    continue
  }

  $sqlJobs[$jobKey] = @{
    sourceHostname = $row.sourceHostname
    targetHost     = $targetHost
    cluster        = $row.Cluster
    srcInstance    = $srcInstance
    tgtInstance    = $tgtInstance
    dataPath       = $dataPath
    logPath        = $logPath
  }
}

Write-Host "Found $($sqlJobs.Count) unique SQL export job(s)" -ForegroundColor Green

# --- Load/create state CSV ---

if (-not (Test-Path $workingDir)) {
  New-Item -ItemType Directory -Path $workingDir -Force | Out-Null
}
$workingDir = (Resolve-Path $workingDir).Path

$stateFile = Join-Path $workingDir "sql_state.csv"
$stateData = [ordered]@{}

if (Test-Path $stateFile) {
  Write-Host "Loading existing state from: $stateFile" -ForegroundColor Yellow
  $existingState = Import-Csv -Path $stateFile
  foreach ($row in $existingState) {
    $stateData[$row.JobKey] = $row
  }
}

# Helper to save state
function Save-State {
  $stateData.Values | Export-Csv -Path $stateFile -NoTypeInformation
}

# Initialize state for each job from the CSV
foreach ($jobKey in $sqlJobs.Keys) {
  $job = $sqlJobs[$jobKey]

  if (-not $stateData.Contains($jobKey)) {
    $stateData[$jobKey] = [PSCustomObject]@{
      JobKey          = $jobKey
      SourceHostname  = $job.sourceHostname
      TargetHost      = $job.targetHost
      Cluster         = $job.cluster
      SrcInstance     = $job.srcInstance
      TgtInstance     = $job.tgtInstance
      DataPath        = $job.dataPath
      LogPath         = $job.logPath
      Status          = 'Pending'
      AsyncRequestId  = ''
      SrcInstanceFid  = ''
      TgtInstanceFid  = ''
      StartTime       = ''
      LastChecked     = ''
      LastMessage     = ''
      ErrorMessage    = ''
    }
  } else {
    $existing = $stateData[$jobKey]
    $existing.SrcInstance = $job.srcInstance
    $existing.TgtInstance = $job.tgtInstance
    $existing.DataPath = $job.dataPath
    $existing.LogPath = $job.logPath
    if ($existing.Status -eq 'Failed' -and $RetryFailed) {
      Write-Host "  RETRY: $($job.sourceHostname) -> $($job.targetHost)" -ForegroundColor Yellow
      $existing.Status = 'Pending'
      $existing.ErrorMessage = ''
      $existing.AsyncRequestId = ''
      $existing.SrcInstanceFid = ''
      $existing.TgtInstanceFid = ''
    }
  }
}

Save-State

# --- Status check pass: check initiated jobs ---

Write-Host ""
Write-Host "--- Status Check ---" -ForegroundColor Cyan

$initiatedJobs = @($stateData.Values | Where-Object { $_.Status -eq 'Initiated' })

if ($initiatedJobs.Count -eq 0) {
  Write-Host "No initiated jobs to check." -ForegroundColor DarkGray
} else {
  Write-Host "Checking status of $($initiatedJobs.Count) initiated job(s)..." -ForegroundColor Cyan

  foreach ($state in $initiatedJobs) {
    Write-Host "  Checking: $($state.SourceHostname)\$($state.SrcInstance) -> $($state.TargetHost)\$($state.TgtInstance)..."

    if ([string]::IsNullOrEmpty($state.SrcInstanceFid)) {
      Write-Host "    No SrcInstanceFid recorded, cannot check status." -ForegroundColor Yellow
      continue
    }

    try {
      $eventData = Invoke-RscQuery -Query $queryGetEvents -Variables @{
        filters = @{
          lastActivityType = @("Recovery")
          objectType = @("Mssql")
          lastUpdatedTimeGt = $state.StartTime
        }
        first = 50
      }

      $recoveryEvents = @($eventData.activitySeriesConnection.edges.node | Where-Object {
        $_.lastActivityType -eq 'Recovery' -and $_.objectType -eq 'Mssql'
      })

      if ($recoveryEvents.Count -eq 0) {
        Write-Host "    No recovery events found yet. Still pending." -ForegroundColor DarkGray
      } else {
        $successCount = 0
        $failedCount = 0
        $runningCount = 0
        $latestMessage = ''

        foreach ($event in $recoveryEvents) {
          $eventMessage = ''
          if ($event.activityConnection.nodes.Count -gt 0) {
            $eventMessage = $event.activityConnection.nodes[0].message
          }
          if ([string]::IsNullOrEmpty($latestMessage)) {
            $latestMessage = $eventMessage
          }

          switch ($event.lastActivityStatus) {
            'Success'  { $successCount++ }
            { $_ -in @('TaskFailed', 'Failure', 'Failed') } { $failedCount++ }
            default    { $runningCount++ }
          }
        }

        $state.LastChecked = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
        $state.LastMessage = $latestMessage

        if ($failedCount -gt 0) {
          $state.Status = 'Failed'
          $state.ErrorMessage = "Failed: $failedCount, Success: $successCount, Running: $runningCount"
          Write-Host "    FAILED: $failedCount failed, $successCount succeeded, $runningCount running" -ForegroundColor Red
        } elseif ($runningCount -gt 0) {
          Write-Host "    IN PROGRESS: $runningCount running, $successCount succeeded" -ForegroundColor DarkGray
        } else {
          $state.Status = 'Success'
          Write-Host "    SUCCESS: All $successCount database(s) exported" -ForegroundColor Green
        }
      }
    } catch {
      Write-Host "    ERROR checking status: $($_.Exception.Message)" -ForegroundColor Red
    }
  }

  Save-State
}

# --- Initiation pass: process pending jobs ---

if ($CheckOnly) {
  Write-Host ""
  Write-Host "CheckOnly mode - skipping initiation of new jobs." -ForegroundColor DarkGray
} else {
  Write-Host ""
  Write-Host "--- SQL Export Initiation ---" -ForegroundColor Cyan

  $pendingJobs = @($sqlJobs.Keys | Where-Object {
    $stateData[$_].Status -eq 'Pending'
  })

  $skipCount = $sqlJobs.Count - $pendingJobs.Count
  if ($skipCount -gt 0) {
    Write-Host "Skipping $skipCount job(s) (already initiated, completed, or failed)" -ForegroundColor DarkGray
  }

  if ($pendingJobs.Count -eq 0) {
    Write-Host "No pending jobs to initiate." -ForegroundColor DarkGray
  } else {
    Write-Host "Processing $($pendingJobs.Count) pending SQL export job(s)..." -ForegroundColor Cyan
    Write-Host ""

    $jobIndex = 0
    foreach ($jobKey in $pendingJobs) {
      $jobIndex++
      $job = $sqlJobs[$jobKey]
      $state = $stateData[$jobKey]
      $srcName = $job.sourceHostname
      $tgtName = $job.targetHost
      $srcInst = $job.srcInstance
      $tgtInst = $job.tgtInstance

      Write-Host "=== SQL Job $jobIndex/$($pendingJobs.Count): $srcName\$srcInst -> $tgtName\$tgtInst ===" -ForegroundColor Cyan

      try {
        # Step 1: Find source MSSQL host in RSC
        Write-Host "  Looking up source host '$srcName'..."
        $srcHostData = Invoke-RscQuery -Query $queryGetMssqlHostsWithCluster -Variables @{
          first = 50
          filter = @(
            @{ field = "NAME"; texts = @($srcName) }
            @{ field = "IS_RELIC"; texts = @("false") }
            @{ field = "IS_REPLICATED"; texts = @("false") }
          )
          sortBy = "NAME"
          sortOrder = "ASC"
        }

        $srcHosts = @($srcHostData.mssqlTopLevelDescendants.edges.node | Where-Object {
          $_.name -eq $srcName -and $_.cluster.name -eq $job.cluster
        })
        if ($srcHosts.Count -eq 0) {
          throw "Source MSSQL host '$srcName' not found on cluster '$($job.cluster)' in RSC."
        }
        $srcHost = $srcHosts[0]
        $srcHostId = $srcHost.id
        $srcClusterId = $srcHost.cluster.id
        $srcClusterName = $srcHost.cluster.name
        $connectivity = $srcHost.physicalHostMetadata.connectionStatus.connectivity
        Write-Host "  Found source host: $srcName (cluster: $srcClusterName, status: $connectivity)" -ForegroundColor Green

        # Step 2: Find source SQL instance on source host
        Write-Host "  Looking up source SQL instance '$srcInst' on '$srcName'..."
        $srcInstData = Invoke-RscQuery -Query $queryGetMssqlInstances -Variables @{
          fid = $srcHostId
          filter = @(
            @{ field = "IS_RELIC"; texts = @("false") }
            @{ field = "IS_REPLICATED"; texts = @("false") }
            @{ field = "IS_ARCHIVED"; texts = @("false") }
          )
          typeFilter = @("MssqlInstance")
        }

        $srcInstances = @($srcInstData.hierarchyObject.childConnection.edges.node | Where-Object {
          $_.name -eq $srcInst
        })
        if ($srcInstances.Count -eq 0) {
          $allInstances = @($srcInstData.hierarchyObject.childConnection.edges.node | ForEach-Object { $_.name })
          throw "Source SQL instance '$srcInst' not found on '$srcName'. Available: $($allInstances -join ', ')"
        }
        $srcInstanceFid = $srcInstances[0].id
        Write-Host "  Found source instance: $srcInst (fid: $srcInstanceFid)" -ForegroundColor Green

        $state.SrcInstanceFid = $srcInstanceFid

        # Step 3: Find target MSSQL host on same cluster
        Write-Host "  Looking up target host '$tgtName' on cluster '$srcClusterName'..."
        $tgtHostData = Invoke-RscQuery -Query $queryGetMssqlHosts -Variables @{
          filter = @(
            @{ field = "NAME"; texts = @("") }
            @{ field = "CLUSTER_ID"; texts = @($srcClusterId) }
            @{ field = "IS_RELIC"; texts = @("false") }
            @{ field = "IS_REPLICATED"; texts = @("false") }
            @{ field = "IS_ARCHIVED"; texts = @("false") }
          )
          typeFilter = @("PhysicalHost", "WindowsCluster")
        }

        $tgtHosts = @($tgtHostData.mssqlTopLevelDescendants.edges.node | Where-Object {
          $_.name -eq $tgtName
        })
        if ($tgtHosts.Count -eq 0) {
          $allHosts = @($tgtHostData.mssqlTopLevelDescendants.edges.node | ForEach-Object { $_.name })
          throw "Target MSSQL host '$tgtName' not found on cluster '$srcClusterName'. Available: $($allHosts -join ', ')"
        }
        $tgtHostId = $tgtHosts[0].id
        Write-Host "  Found target host: $tgtName (fid: $tgtHostId)" -ForegroundColor Green

        # Step 4: Find target SQL instance on target host
        Write-Host "  Looking up target SQL instance '$tgtInst' on '$tgtName'..."
        $tgtInstData = Invoke-RscQuery -Query $queryGetMssqlInstances -Variables @{
          fid = $tgtHostId
          filter = @(
            @{ field = "IS_RELIC"; texts = @("false") }
            @{ field = "IS_REPLICATED"; texts = @("false") }
            @{ field = "IS_ARCHIVED"; texts = @("false") }
          )
          typeFilter = @("MssqlInstance")
        }

        $tgtInstances = @($tgtInstData.hierarchyObject.childConnection.edges.node | Where-Object {
          $_.name -eq $tgtInst
        })
        if ($tgtInstances.Count -eq 0) {
          $allInstances = @($tgtInstData.hierarchyObject.childConnection.edges.node | ForEach-Object { $_.name })
          throw "Target SQL instance '$tgtInst' not found on '$tgtName'. Available: $($allInstances -join ', ')"
        }
        $tgtInstanceFid = $tgtInstances[0].id
        Write-Host "  Found target instance: $tgtInst (fid: $tgtInstanceFid)" -ForegroundColor Green

        $state.TgtInstanceFid = $tgtInstanceFid

        # Step 5: Execute bulk export mutation
        $recoveryTimestampMs = [long]([DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds())
        Write-Host "  Initiating bulk export (recovery point: $recoveryTimestampMs)..."

        $exportResult = Invoke-RscQuery -Query $mutationBulkExport -Variables @{
          input = @{
            config = @{
              finishRecovery     = $true
              recoveryPoint      = @{ timestampMs = $recoveryTimestampMs }
              sourceInstanceIds  = @($srcInstanceFid)
              allowOverwrite     = $false
              targetDataFilePath = $job.dataPath
              targetLogFilePath  = $job.logPath
              targetInstanceId   = $tgtInstanceFid
            }
          }
        }

        $asyncId = $exportResult.bulkExportMssqlDatabases.id
        Write-Host "  Bulk export initiated. Async request ID: $asyncId" -ForegroundColor Green

        $state.Status = 'Initiated'
        $state.AsyncRequestId = $asyncId
        $state.StartTime = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ss.fffZ')

      } catch {
        Write-Host "  ERROR: $($_.Exception.Message)" -ForegroundColor Red
        $state.Status = 'Failed'
        $state.ErrorMessage = $_.Exception.Message
      }

      Save-State
      Write-Host ""
    }
  }
}

# --- Summary ---

Write-Host "======================================" -ForegroundColor Cyan
Write-Host "SQL Export Summary" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan

$statusGroups = $stateData.Values | Group-Object -Property Status
foreach ($group in $statusGroups | Sort-Object Name) {
  $color = switch ($group.Name) {
    'Success'   { 'Green' }
    'Initiated' { 'Cyan' }
    'Pending'   { 'DarkGray' }
    'Failed'    { 'Red' }
    default     { 'White' }
  }
  Write-Host "  $($group.Name): $($group.Count)" -ForegroundColor $color
}
Write-Host ""

foreach ($state in $stateData.Values) {
  $statusLabel = $state.Status
  $color = switch ($statusLabel) {
    'Success'   { 'Green' }
    'Initiated' { 'Cyan' }
    'Pending'   { 'DarkGray' }
    'Failed'    { 'Red' }
    default     { 'White' }
  }
  $detail = switch ($statusLabel) {
    'Initiated' { "async: $($state.AsyncRequestId)" }
    'Failed'    { $state.ErrorMessage }
    'Success'   { $state.LastMessage }
    default     { "$($state.SrcInstance) -> $($state.TgtInstance)" }
  }
  Write-Host "  [$statusLabel] $($state.SourceHostname)\$($state.SrcInstance) -> $($state.TargetHost)\$($state.TgtInstance): $detail" -ForegroundColor $color
}

Write-Host ""
Write-Host "State file: $stateFile" -ForegroundColor Cyan
Write-Host "SQL export processing complete." -ForegroundColor Green
