---
- name: Run shell command
  hosts: all
  remote_user: root
  gather_facts: no
  tasks:
    - name: Shell command
      shell: |
        killall fio
        fio iotest.fio &
      register: command_output
    - debug:
        var: command_output.stdout_lines
