# Config file for pure_epic_snap_copy_individual.sh
# Only include variables that differ from the defaults in the main script.
# Usage: ./pure_epic_snap_copy_individual.sh /path/to/this.conf

# Name of the Epic instance (used in log filenames)
INSTANCE_NAME="dctst"

# Whether or not to execute the Epic IRIS freeze / thaw
EXECUTE_EPIC="false"

# Pure array hostname and username
PURE_ARRAY="purepcchetp2.chop.edu"
PURE_USER="svcrbkpure"

# Pure - This is the name of the source IRIS ODB volume on the Pure array
SOURCE_VOLUME="IRSDBXDL2/IRSDBXDL2-EPICDCTSTVG"
# Pure - This suffix will be appended to the Volume Snap along with YYYY-MM-DD
SOURCE_SNAP_SUFFIX="rubriksnap"
# Pure - Target IRIS volume, the name of the target volume mounted on the Proxy VM that will be refreshed
TARGET_VOLUME="dctst"

# Mount point of the IRIS DB instance
MOUNT_POINT="/mnt/dctst"
# The /dev/<lv_name> that will be mounted to the mount point
DEV_LV="/dev/mapper/epicdctstvg-dctstlv"

# Epic IRIS freeze / thaw commands
EPIC_FREEZE_CMD="/epic/dctst/bin/instfreeze"
EPIC_THAW_CMD="/epic/dctst/bin/instthaw"
EPIC_AUTOTHAW_CMD="nohup sh -c '(sleep 8m && ${EPIC_THAW_CMD}) > /dev/null 2>&1 &'"

# Epic IRIS ODB server hostname and user
EPIC_SERVER="irsdbxdl2"
EPIC_ID="root"
